//! A two-token constant-product automated market maker (`x * y = k`).
//!
//! Liquidity providers `deposit` a pair of tokens and receive pool shares in
//! return; they `withdraw` those shares later for a proportional slice of the
//! reserves (plus accrued fees). Traders `swap` one token for the other at a
//! price set by the pool's reserves, paying a 0.3% fee that stays in the pool
//! and grows the constant product `k` over time.
//!
//! Pool shares are tracked internally as a simple `i128` ledger — this pool
//! does not issue a separate share-token contract, keeping the example
//! self-contained. The two reserve tokens are any contracts implementing the
//! standard Soroban token interface (e.g. Stellar Asset Contracts).
//!
//! Generated by [soroban-forge](https://github.com/soroban-forge-labs/soroban-forge).

#![no_std]

use soroban_sdk::{
    contract, contracterror, contractimpl, contracttype, panic_with_error, token, Address, Env,
};

/// Swap fee numerator/denominator: 0.3% (997/1000), the Uniswap-v2 standard.
/// The 0.3% stays in the pool, so `k` grows monotonically with trading.
const FEE_NUM: i128 = 997;
const FEE_DEN: i128 = 1000;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum Error {
    /// A supplied amount was zero or negative.
    InvalidAmount = 1,
    /// The pool has no liquidity yet for the requested operation.
    InsufficientLiquidity = 2,
    /// A swap would cost more input than the caller's stated maximum.
    SlippageExceeded = 3,
    /// A deposit's implied ratio fell outside the caller's tolerance, or a
    /// withdrawal returned less than the caller's stated minimum.
    RatioOutOfRange = 4,
}

#[contracttype]
#[derive(Clone)]
pub enum DataKey {
    /// Address of reserve token A.
    TokenA,
    /// Address of reserve token B.
    TokenB,
    /// Current reserve of token A held by the pool.
    ReserveA,
    /// Current reserve of token B held by the pool.
    ReserveB,
    /// Total pool shares issued.
    TotalShares,
    /// Pool shares owned by a single provider.
    Shares(Address),
}

fn get_token_a(env: &Env) -> Address {
    env.storage().instance().get(&DataKey::TokenA).unwrap()
}

fn get_token_b(env: &Env) -> Address {
    env.storage().instance().get(&DataKey::TokenB).unwrap()
}

fn get_reserve_a(env: &Env) -> i128 {
    env.storage().instance().get(&DataKey::ReserveA).unwrap_or(0)
}

fn get_reserve_b(env: &Env) -> i128 {
    env.storage().instance().get(&DataKey::ReserveB).unwrap_or(0)
}

fn get_total_shares(env: &Env) -> i128 {
    env.storage()
        .instance()
        .get(&DataKey::TotalShares)
        .unwrap_or(0)
}

fn put_reserves(env: &Env, reserve_a: i128, reserve_b: i128) {
    env.storage().instance().set(&DataKey::ReserveA, &reserve_a);
    env.storage().instance().set(&DataKey::ReserveB, &reserve_b);
}

fn get_shares(env: &Env, owner: &Address) -> i128 {
    env.storage()
        .instance()
        .get(&DataKey::Shares(owner.clone()))
        .unwrap_or(0)
}

fn mint_shares(env: &Env, to: &Address, amount: i128) {
    let new_owner = get_shares(env, to) + amount;
    let new_total = get_total_shares(env) + amount;
    env.storage()
        .instance()
        .set(&DataKey::Shares(to.clone()), &new_owner);
    env.storage()
        .instance()
        .set(&DataKey::TotalShares, &new_total);
}

fn burn_shares(env: &Env, from: &Address, amount: i128) {
    let owned = get_shares(env, from);
    if owned < amount {
        panic_with_error!(env, Error::InsufficientLiquidity);
    }
    env.storage()
        .instance()
        .set(&DataKey::Shares(from.clone()), &(owned - amount));
    env.storage()
        .instance()
        .set(&DataKey::TotalShares, &(get_total_shares(env) - amount));
}

/// Integer square root via Newton's method — used to size the first deposit's
/// shares as `sqrt(amount_a * amount_b)`, matching Uniswap-v2.
fn sqrt(value: i128) -> i128 {
    if value <= 0 {
        return 0;
    }
    let mut x = value;
    let mut y = (x + 1) / 2;
    while y < x {
        x = y;
        y = (x + value / x) / 2;
    }
    x
}

#[contract]
pub struct LiquidityPool;

#[contractimpl]
impl LiquidityPool {
    /// Initialise the pool over two distinct token contracts. Reserves and
    /// shares start at zero.
    pub fn __constructor(env: Env, token_a: Address, token_b: Address) {
        env.storage().instance().set(&DataKey::TokenA, &token_a);
        env.storage().instance().set(&DataKey::TokenB, &token_b);
        env.storage().instance().set(&DataKey::ReserveA, &0i128);
        env.storage().instance().set(&DataKey::ReserveB, &0i128);
        env.storage().instance().set(&DataKey::TotalShares, &0i128);
    }

    /// Deposit liquidity and receive pool shares.
    ///
    /// The first deposit sets the price and may use any positive amounts. For
    /// later deposits, `amount_a` and `amount_b` must be within
    /// `[min_a, ..]`/`[min_b, ..]` of the pool's current ratio; the exact
    /// amounts pulled are whatever the ratio requires. Returns the number of
    /// shares minted.
    pub fn deposit(
        env: Env,
        to: Address,
        amount_a: i128,
        min_a: i128,
        amount_b: i128,
        min_b: i128,
    ) -> i128 {
        to.require_auth();
        if amount_a <= 0 || amount_b <= 0 {
            panic_with_error!(&env, Error::InvalidAmount);
        }

        let reserve_a = get_reserve_a(&env);
        let reserve_b = get_reserve_b(&env);
        let total_shares = get_total_shares(&env);

        // Resolve the actual amounts to pull, respecting the current ratio.
        let (final_a, final_b) = if reserve_a == 0 && reserve_b == 0 {
            (amount_a, amount_b)
        } else {
            let implied_b = amount_a * reserve_b / reserve_a;
            if implied_b <= amount_b {
                if implied_b < min_b {
                    panic_with_error!(&env, Error::RatioOutOfRange);
                }
                (amount_a, implied_b)
            } else {
                let implied_a = amount_b * reserve_a / reserve_b;
                if implied_a > amount_a || implied_a < min_a {
                    panic_with_error!(&env, Error::RatioOutOfRange);
                }
                (implied_a, amount_b)
            }
        };

        // Pull the tokens into the pool.
        let pool = env.current_contract_address();
        token::Client::new(&env, &get_token_a(&env)).transfer(&to, &pool, &final_a);
        token::Client::new(&env, &get_token_b(&env)).transfer(&to, &pool, &final_b);

        // Mint shares.
        let minted = if total_shares == 0 {
            sqrt(final_a * final_b)
        } else {
            let by_a = final_a * total_shares / reserve_a;
            let by_b = final_b * total_shares / reserve_b;
            if by_a < by_b {
                by_a
            } else {
                by_b
            }
        };
        if minted <= 0 {
            panic_with_error!(&env, Error::InsufficientLiquidity);
        }

        put_reserves(&env, reserve_a + final_a, reserve_b + final_b);
        mint_shares(&env, &to, minted);
        minted
    }

    /// Swap to buy exactly `out` units of one token, paying at most `in_max`
    /// of the other. When `buy_a` is true the caller buys token A with token B;
    /// otherwise they buy token B with token A. Returns the input actually
    /// spent.
    pub fn swap(env: Env, to: Address, buy_a: bool, out: i128, in_max: i128) -> i128 {
        to.require_auth();
        if out <= 0 || in_max <= 0 {
            panic_with_error!(&env, Error::InvalidAmount);
        }

        let reserve_a = get_reserve_a(&env);
        let reserve_b = get_reserve_b(&env);

        // (reserve_in, reserve_out) depend on the direction.
        let (reserve_in, reserve_out) = if buy_a {
            (reserve_b, reserve_a)
        } else {
            (reserve_a, reserve_b)
        };
        if out >= reserve_out || reserve_in == 0 {
            panic_with_error!(&env, Error::InsufficientLiquidity);
        }

        // Constant-product with a 0.3% fee on the input. Solve for the minimum
        // input that keeps `k` non-decreasing, then round up by one unit:
        //   in = reserve_in * out * FEE_DEN
        //        / ((reserve_out - out) * FEE_NUM)  + 1
        let numerator = reserve_in * out * FEE_DEN;
        let denominator = (reserve_out - out) * FEE_NUM;
        let in_amount = numerator / denominator + 1;
        if in_amount > in_max {
            panic_with_error!(&env, Error::SlippageExceeded);
        }

        let pool = env.current_contract_address();
        let (token_in, token_out) = if buy_a {
            (get_token_b(&env), get_token_a(&env))
        } else {
            (get_token_a(&env), get_token_b(&env))
        };
        token::Client::new(&env, &token_in).transfer(&to, &pool, &in_amount);
        token::Client::new(&env, &token_out).transfer(&pool, &to, &out);

        // Update reserves according to direction.
        if buy_a {
            put_reserves(&env, reserve_a - out, reserve_b + in_amount);
        } else {
            put_reserves(&env, reserve_a + in_amount, reserve_b - out);
        }
        in_amount
    }

    /// Redeem `share_amount` shares for a proportional slice of both reserves,
    /// requiring at least `min_a`/`min_b` out as a slippage guard. Returns the
    /// `(amount_a, amount_b)` withdrawn.
    pub fn withdraw(
        env: Env,
        to: Address,
        share_amount: i128,
        min_a: i128,
        min_b: i128,
    ) -> (i128, i128) {
        to.require_auth();
        if share_amount <= 0 {
            panic_with_error!(&env, Error::InvalidAmount);
        }

        let total_shares = get_total_shares(&env);
        if total_shares == 0 {
            panic_with_error!(&env, Error::InsufficientLiquidity);
        }

        let reserve_a = get_reserve_a(&env);
        let reserve_b = get_reserve_b(&env);
        let out_a = reserve_a * share_amount / total_shares;
        let out_b = reserve_b * share_amount / total_shares;
        if out_a < min_a || out_b < min_b {
            panic_with_error!(&env, Error::RatioOutOfRange);
        }

        burn_shares(&env, &to, share_amount);

        let pool = env.current_contract_address();
        token::Client::new(&env, &get_token_a(&env)).transfer(&pool, &to, &out_a);
        token::Client::new(&env, &get_token_b(&env)).transfer(&pool, &to, &out_b);

        put_reserves(&env, reserve_a - out_a, reserve_b - out_b);
        (out_a, out_b)
    }

    /// The current `(reserve_a, reserve_b)`.
    pub fn get_reserves(env: Env) -> (i128, i128) {
        (get_reserve_a(&env), get_reserve_b(&env))
    }

    /// Pool shares owned by `owner`.
    pub fn shares(env: Env, owner: Address) -> i128 {
        get_shares(&env, &owner)
    }

    /// Total pool shares issued.
    pub fn total_shares(env: Env) -> i128 {
        get_total_shares(&env)
    }

    /// The two reserve token addresses, `(token_a, token_b)`.
    pub fn tokens(env: Env) -> (Address, Address) {
        (get_token_a(&env), get_token_b(&env))
    }
}

#[cfg(test)]
mod test;
