//! # soroban-forge-ci-presets
//!
//! `soroban-forge ci-init --provider github` — writes CI/CD workflows for a
//! Soroban contract project.

use clap::{Arg, ArgAction, ArgMatches, Command};
use include_dir::{include_dir, Dir};
use serde::Deserialize;
use soroban_forge_core::render::{render_str, Vars};
use soroban_forge_core::{ForgeContext, ForgeError, ForgePlugin, Result};
use std::io::Write;
use std::path::Path;

static PRESETS: Dir<'_> = include_dir!("$CARGO_MANIFEST_DIR/../../presets");

const BASE_WORKFLOWS: &[&str] = &["build-test.yml", "contract-size.yml"];
const MATRIX_WORKFLOW: &str = "build-test-matrix.yml";
const DEPLOY_WORKFLOW: &str = "testnet-deploy.yml";
const RELEASE_WORKFLOW: &str = "release.yml";
const SECURITY_SCAN_WORKFLOW: &str = "security-scan.yml";
const COVERAGE_WORKFLOW: &str = "coverage.yml";
const ACTIONLINT_WORKFLOW: &str = "actionlint.yml";
const DENY_TOML: &str = "deny.toml";
const HEALTHCHECK_WORKFLOW: &str = "testnet-healthcheck.yml";
const STALE_WORKFLOW: &str = "stale.yml";
pub const DEFAULT_MSRV: &str = "1.84";
pub const DEFAULT_MAX_SIZE: u64 = 65_536;
const DEPENDABOT_CONFIG: &str = "dependabot.yml";

/// Substring that must appear in the first 512 bytes of a file for it to be
/// considered forge-generated.  All preset templates begin with a comment
/// containing this string (e.g. `# Generated by \`soroban-forge ci-init\``).
pub const FORGE_MARKER: &str = "Generated by";

pub fn available_providers() -> Vec<&'static str> {
    let mut names: Vec<&'static str> = PRESETS
        .dirs()
        .filter_map(|d| d.path().file_name().and_then(|n| n.to_str()))
        .collect();
    names.sort_unstable();
    names
}

/// Parse and validate a comma-separated provider string such as `"github,gitlab"`.
///
/// Returns a `Vec` of de-duplicated, trimmed provider names, or an
/// [`ForgeError::InvalidArgument`] listing every unrecognised name.
pub fn parse_providers(raw: &str) -> Result<Vec<String>> {
    let known = available_providers();
    let mut providers: Vec<String> = Vec::new();
    let mut unknown: Vec<String> = Vec::new();

    for token in raw.split(',') {
        let name = token.trim().to_string();
        if name.is_empty() {
            continue;
        }
        if !known.contains(&name.as_str()) {
            unknown.push(name);
        } else if !providers.contains(&name) {
            providers.push(name);
        }
    }

    if !unknown.is_empty() {
        return Err(ForgeError::InvalidArgument(format!(
            "unknown provider(s) `{}` (available: {})",
            unknown.join(", "),
            known.join(", ")
        )));
    }
    if providers.is_empty() {
        return Err(ForgeError::InvalidArgument(
            "at least one provider must be specified".into(),
        ));
    }
    Ok(providers)
}

pub fn output_dir(provider: &str) -> &'static str {
    match provider {
        "github" => ".github/workflows",
        "gitlab" | "bitbucket" | "azure" | "woodpecker" => ".",
        "circleci" => ".circleci",
        "buildkite" => ".buildkite",
        _ => unreachable!("validated against available_providers()"),
    }
}

#[derive(Deserialize)]
struct Manifest {
    package: Package,
}

#[derive(Deserialize)]
struct Package {
    name: String,
}

fn project_name(dir: &Path, ctx: &ForgeContext) -> String {
    if let Some(name) = ctx.config.as_ref().and_then(|c| c.project.name.clone()) {
        return name;
    }
    let manifest_path = dir.join("Cargo.toml");
    if let Ok(raw) = std::fs::read_to_string(&manifest_path) {
        if let Ok(manifest) = toml::from_str::<Manifest>(&raw) {
            return manifest.package.name;
        }
    }
    dir.file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_else(|| "contract".to_string())
}

#[derive(Debug, Default, Clone)]
pub struct GenerateOptions {
    pub deploy: bool,
    pub security_scan: bool,
    pub coverage: bool,
    pub actionlint: bool,
    pub healthcheck: bool,
    pub matrix: bool,
    pub stale: bool,
    pub msrv: Option<String>,
    pub dependabot: bool,
    pub max_size: Option<u64>,
}

pub fn generate(
    dir: &Path,
    provider: &str,
    project_name: &str,
    _deploy: bool,
    release: bool,
    opts: &GenerateOptions,
    force: bool,
) -> Result<Vec<String>> {
    let provider_dir = PRESETS.get_dir(provider).ok_or_else(|| {
        ForgeError::InvalidArgument(format!(
            "unknown provider `{provider}` (available: {})",
            available_providers().join(", ")
        ))
    })?;

    let mut vars = Vars::new();
    let max_size = opts.max_size.unwrap_or(DEFAULT_MAX_SIZE);
    vars.insert("project_name".into(), project_name.to_string());
    vars.insert("crate_name".into(), project_name.replace('-', "_"));
    vars.insert(
        "msrv".into(),
        opts.msrv
            .clone()
            .unwrap_or_else(|| DEFAULT_MSRV.to_string()),
    );
    vars.insert("max_size".into(), max_size.to_string());

    let out_rel = output_dir(provider);
    let out_dir = dir.join(out_rel);
    std::fs::create_dir_all(&out_dir)
        .map_err(ForgeError::io(format!("creating {}", out_dir.display())))?;

    let mut selected: Vec<(&str, Option<&str>)> = match provider {
        "github" => {
            let mut list: Vec<(&str, Option<&str>)> =
                BASE_WORKFLOWS.iter().map(|n| (*n, None)).collect();
            if opts.deploy {
                list.push((DEPLOY_WORKFLOW, None));
            }
            if opts.security_scan {
                list.push((SECURITY_SCAN_WORKFLOW, None));
                list.push((DENY_TOML, Some(".")));
            }
            if opts.coverage {
                list.push((COVERAGE_WORKFLOW, None));
            }
            if opts.actionlint {
                list.push((ACTIONLINT_WORKFLOW, None));
            }
            if opts.healthcheck {
                list.push((HEALTHCHECK_WORKFLOW, None));
            }
            if opts.stale {
                list.push((STALE_WORKFLOW, None));
            }
            if release {
                list.push((RELEASE_WORKFLOW, None));
            }
            if opts.matrix {
                list.push((MATRIX_WORKFLOW, None));
            }
            if opts.dependabot {
                list.push((DEPENDABOT_CONFIG, Some(".github")));
            }
            list
        }
        "gitlab" => vec![(".gitlab-ci.yml", None)],
        "bitbucket" => vec![("bitbucket-pipelines.yml", None)],
        "azure" => vec![("azure-pipelines.yml", None)],
        "circleci" => vec![("config.yml", None)],
        "woodpecker" => vec![(".woodpecker.yml", None)],
        "buildkite" => vec![("pipeline.yml", None)],
        _ => {
            return Err(ForgeError::InvalidArgument(format!(
                "unknown provider `{provider}` (available: {})",
                available_providers().join(", ")
            )));
        }
    };

    let mut written = Vec::new();
    for (name, dest_rel_override) in selected.drain(..) {
        let file = provider_dir
            .get_file(format!("{provider}/{name}"))
            .ok_or_else(|| {
                ForgeError::Template(format!("missing preset file {provider}/{name}"))
            })?;
        let contents = file
            .contents_utf8()
            .ok_or_else(|| ForgeError::Template(format!("preset {name} is not UTF-8")))?;

        let dest_rel = dest_rel_override.unwrap_or(out_rel);
        let dest_dir = dir.join(dest_rel);
        std::fs::create_dir_all(&dest_dir)
            .map_err(ForgeError::io(format!("creating {}", dest_dir.display())))?;
        let out_path = dest_dir.join(name);
        if out_path.exists() && !force {
            return Err(ForgeError::AlreadyExists(out_path));
        }
        std::fs::write(&out_path, render_str(contents, &vars))
            .map_err(ForgeError::io(format!("writing {}", out_path.display())))?;

        let rel_path = if dest_rel == "." {
            name.to_string()
        } else {
            format!("{dest_rel}/{name}")
        };
        written.push(rel_path);
    }
    Ok(written)
}

/// Returns the list of paths that the named provider would write for a full
/// `generate` run (all flags enabled).  Used by `remove` to know which files
/// to look for.
fn all_target_paths(dir: &Path, provider: &str) -> Vec<std::path::PathBuf> {
    let out_rel = output_dir(provider);
    let out_dir = dir.join(out_rel);
    let mut paths: Vec<std::path::PathBuf> = match provider {
        "github" => {
            // The complete set of files the github preset can ever write.
            let workflow_dir = out_dir.clone();
            let root_dir = dir.to_path_buf();
            let github_dir = dir.join(".github");
            vec![
                workflow_dir.join("build-test.yml"),
                workflow_dir.join("contract-size.yml"),
                workflow_dir.join(DEPLOY_WORKFLOW),
                workflow_dir.join(SECURITY_SCAN_WORKFLOW),
                root_dir.join(DENY_TOML),
                workflow_dir.join(COVERAGE_WORKFLOW),
                workflow_dir.join(ACTIONLINT_WORKFLOW),
                workflow_dir.join(HEALTHCHECK_WORKFLOW),
                workflow_dir.join(STALE_WORKFLOW),
                workflow_dir.join(RELEASE_WORKFLOW),
                workflow_dir.join(MATRIX_WORKFLOW),
                github_dir.join(DEPENDABOT_CONFIG),
            ]
        }
        "gitlab" => vec![out_dir.join(".gitlab-ci.yml")],
        "bitbucket" => vec![out_dir.join("bitbucket-pipelines.yml")],
        "azure" => vec![out_dir.join("azure-pipelines.yml")],
        "circleci" => vec![out_dir.join("config.yml")],
        "woodpecker" => vec![out_dir.join(".woodpecker.yml")],
        "buildkite" => vec![dir.join(".buildkite").join("pipeline.yml")],
        _ => vec![],
    };
    // Keep only paths that actually exist on disk.
    paths.retain(|p| p.exists());
    paths
}

/// Returns true when the first 512 bytes of `path` contain [`FORGE_MARKER`].
fn is_forge_generated(path: &Path) -> bool {
    use std::io::Read;
    let Ok(mut f) = std::fs::File::open(path) else {
        return false;
    };
    let mut buf = [0u8; 512];
    let n = f.read(&mut buf).unwrap_or(0);
    let head = std::str::from_utf8(&buf[..n]).unwrap_or("");
    head.contains(FORGE_MARKER)
}

/// Delete the files that `provider`'s preset would have written.
///
/// * Skips files that don't exist.
/// * Refuses to delete a file whose header doesn't contain [`FORGE_MARKER`]
///   unless `force` is `true`.
/// * Returns the list of successfully removed paths (relative to `dir`).
pub fn remove(dir: &Path, provider: &str, force: bool) -> Result<Vec<String>> {
    // Validate provider.
    if !available_providers().contains(&provider) {
        return Err(ForgeError::InvalidArgument(format!(
            "unknown provider `{provider}` (available: {})",
            available_providers().join(", ")
        )));
    }

    let candidates = all_target_paths(dir, provider);

    let mut removed = Vec::new();
    for path in &candidates {
        if !path.exists() {
            continue;
        }
        if !force && !is_forge_generated(path) {
            return Err(ForgeError::InvalidArgument(format!(
                "{} does not look forge-generated (no `{}` header). \
                 Pass --force to remove it anyway.",
                path.display(),
                FORGE_MARKER
            )));
        }
        std::fs::remove_file(path)
            .map_err(ForgeError::io(format!("removing {}", path.display())))?;

        // Build a path relative to `dir` for reporting.
        let rel = path
            .strip_prefix(dir)
            .map(|p| p.to_string_lossy().into_owned())
            .unwrap_or_else(|_| path.to_string_lossy().into_owned());
        removed.push(rel);
    }
    Ok(removed)
}

pub fn format_report(
    provider: &str,
    name: &str,
    written: &[impl AsRef<str>],
    release: bool,
    opts: &GenerateOptions,
) -> String {
    let mut out = format!("wrote {provider} workflows for `{name}`:\n");
    for path in written {
        out.push_str(&format!("  {}\n", path.as_ref()));
    }
    if opts.deploy {
        let secret_kind = if provider == "gitlab" {
            "GitLab CI/CD variable"
        } else {
            "GitHub secret"
        };
        let secret_location = if provider == "gitlab" {
            "  repo -> Settings -> CI/CD -> Variables\n"
        } else {
            "  repo -> Settings -> Secrets and variables -> Actions\n"
        };
        out.push_str(&format!(
            "\nthe deploy workflow needs a {secret_kind} named STELLAR_DEPLOYER_SECRET\n\
             (a funded testnet account's secret key). Add it under:\n\
             {secret_location}"
        ));
    }
    if opts.security_scan {
        out.push_str(
            "\nsecurity-scan: review deny.toml at the project root to tune license and\n\
             vulnerability policies. Install locally with: cargo install cargo-audit cargo-deny\n",
        );
    }
    if opts.dependabot {
        out.push_str(
            "\ndependabot: weekly update PRs for the cargo and github-actions ecosystems.\n\
             Enable Dependabot under: repo -> Settings -> Code security\n",
        );
    }
    if opts.coverage {
        out.push_str(
            "\ncoverage: upload test results to Codecov by adding a repository secret named\n\
             CODECOV_TOKEN. If that secret is missing, the workflow skips the upload gracefully.\n",
        );
    }
    if opts.actionlint {
        out.push_str(
            "\nactionlint: validate generated GitHub workflows in CI with `actionlint` before they merge.\n",
        );
    }
    if opts.healthcheck {
        out.push_str(
            "\ntestnet-healthcheck: the smoke entry point defaults to `version` then `ping`.\n\
             Edit testnet-healthcheck.yml to invoke your contract's real health method.\n",
        );
    }
    if opts.stale {
        out.push_str(
            "\nstale: marks inactive issues and PRs stale, and closes them after the configured grace period.\n\
             The workflow inputs can be adjusted from GitHub Actions -> stale -> Run workflow.\n",
        );
    }
    if opts.matrix {
        let msrv = opts.msrv.as_deref().unwrap_or(DEFAULT_MSRV);
        out.push_str(&format!(
            "\nbuild-test-matrix: the job runs once per toolchain — stable and MSRV {msrv}.\n\
             Pass --msrv <version> to pin a different MSRV, and keep it in sync with\n\
             `rust-version` in Cargo.toml.\n"
        ));
    }
    if release {
        out.push_str("\npush a tag matching `v*.*.*` (e.g. `v0.1.0`) to build the wasm,\n");
        out.push_str("verify the build is reproducible, and publish it to a GitHub Release\n");
        out.push_str(
            "with a SHA256 checksum and detached signatures. Uses the default GITHUB_TOKEN — no secrets needed.\n",
        );
    }
    out
}

fn print_diff(path: &Path, generated: &str) -> Result<()> {
    let temp_path = std::env::temp_dir().join(format!(
        "soroban-forge-ci-init-{}-{}.tmp",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos()
    ));
    let mut temp_file = std::fs::File::create(&temp_path)
        .map_err(ForgeError::io(format!("creating {}", temp_path.display())))?;
    temp_file
        .write_all(generated.as_bytes())
        .map_err(ForgeError::io(format!("writing {}", temp_path.display())))?;

    let left = if path.exists() { path } else { Path::new("/dev/null") };
    let mut cmd = std::process::Command::new("diff");
    cmd.arg("-u").arg("--label").arg("generated").arg("--label").arg(path.to_string_lossy().as_ref());
    cmd.arg(left).arg(&temp_path);
    let output = cmd.output().map_err(ForgeError::io(format!("running diff for {}", path.display())))?;
    let stdout = String::from_utf8_lossy(&output.stdout);
    print!("\n--- {} ---\n{stdout}", path.display());
    std::fs::remove_file(&temp_path).ok();
    Ok(())
}

pub struct CiPresetsPlugin;

impl ForgePlugin for CiPresetsPlugin {
    fn name(&self) -> &'static str {
        "ci-init"
    }

    fn command(&self) -> Command {
        Command::new("ci-init")
            .about("Write CI/CD workflows")
            .arg(
                Arg::new("provider")
                    .long("provider")
                    .default_value("github")
                    .help("CI provider(s) — one of `github`, `gitlab`, `circleci`, `azure`, `bitbucket`, `woodpecker`, `buildkite`, or a comma-separated list (e.g. `github,gitlab`)"),
            )
            .arg(Arg::new("deploy").long("deploy").action(ArgAction::SetTrue))
            .arg(Arg::new("security-scan").long("security-scan").action(ArgAction::SetTrue))
            .arg(Arg::new("coverage").long("coverage").action(ArgAction::SetTrue))
            .arg(Arg::new("actionlint").long("actionlint").action(ArgAction::SetTrue))
            .arg(Arg::new("healthcheck").long("healthcheck").action(ArgAction::SetTrue))
            .arg(Arg::new("matrix").long("matrix").action(ArgAction::SetTrue))
            .arg(Arg::new("stale").long("stale").action(ArgAction::SetTrue))
            .arg(Arg::new("msrv").long("msrv").value_name("VERSION"))
            .arg(Arg::new("max-size").long("max-size").value_name("BYTES").value_parser(clap::value_parser!(u64)))
            .arg(Arg::new("dependabot").long("dependabot").action(ArgAction::SetTrue))
            .arg(Arg::new("release").long("release").action(ArgAction::SetTrue))
            .arg(Arg::new("diff").long("diff").action(ArgAction::SetTrue))
            .arg(Arg::new("path").long("path"))
            .arg(Arg::new("force").long("force").action(ArgAction::SetTrue))
            .arg(
                Arg::new("remove")
                    .long("remove")
                    .action(ArgAction::SetTrue)
                    .help("Remove the files this provider's preset would have written (only forge-generated files; use --force to override)"),
            )
    }

    fn run(&self, matches: &ArgMatches, ctx: &ForgeContext) -> Result<()> {
        let raw_provider = matches.get_one::<String>("provider").expect("has default");
        let providers = parse_providers(raw_provider)?;

        let dir = matches
            .get_one::<String>("path")
            .map(|p| ctx.cwd.join(p))
            .unwrap_or_else(|| ctx.cwd.clone());
        let name = project_name(&dir, ctx);
        let max_size = matches
            .get_one::<u64>("max-size")
            .copied()
            .or_else(|| {
                ctx.config.as_ref().and_then(|c| {
                    c.defaults
                        .ci_init
                        .max_size
                })
            })
            .unwrap_or(DEFAULT_MAX_SIZE);
        let opts = GenerateOptions {
            deploy: matches.get_flag("deploy"),
            security_scan: matches.get_flag("security-scan"),
            coverage: matches.get_flag("coverage"),
            actionlint: matches.get_flag("actionlint"),
            healthcheck: matches.get_flag("healthcheck"),
            matrix: matches.get_flag("matrix"),
            stale: matches.get_flag("stale"),
            msrv: matches.get_one::<String>("msrv").cloned(),
            dependabot: matches.get_flag("dependabot"),
            max_size: Some(max_size),
        };

        // ── --remove ───────────────────────────────────────────────────────
        if matches.get_flag("remove") {
            let force = matches.get_flag("force");
            if ctx.json {
                let mut results = Vec::new();
                for provider in &providers {
                    let removed = remove(&dir, provider, force)?;
                    results.push(serde_json::json!({
                        "provider": provider,
                        "removed_files": removed,
                    }));
                }
                let report = if results.len() == 1 {
                    results.remove(0)
                } else {
                    serde_json::json!(results)
                };
                println!("{}", serde_json::to_string_pretty(&report).unwrap());
            } else {
                for provider in &providers {
                    let removed = remove(&dir, provider, force)?;
                    if !ctx.quiet {
                        if removed.is_empty() {
                            println!("no forge-generated {provider} files found");
                        } else {
                            println!("removed {provider} CI files:");
                            for path in &removed {
                                println!("  {path}");
                            }
                        }
                    }
                }
            }
            return Ok(());
        }

        // ── --diff ─────────────────────────────────────────────────────────
        if matches.get_flag("diff") {
            for provider in &providers {
                let provider_dir = PRESETS.get_dir(provider.as_str()).ok_or_else(|| {
                    ForgeError::InvalidArgument(format!(
                        "unknown provider `{provider}` (available: {})",
                        available_providers().join(", ")
                    ))
                })?;
                let mut selected: Vec<(&str, Option<&str>)> = match provider.as_str() {
                    "github" => {
                        let mut list: Vec<(&str, Option<&str>)> = BASE_WORKFLOWS.iter().map(|n| (*n, None)).collect();
                        if opts.deploy { list.push((DEPLOY_WORKFLOW, None)); }
                        if opts.security_scan { list.push((SECURITY_SCAN_WORKFLOW, None)); list.push((DENY_TOML, Some("."))); }
                        if opts.coverage { list.push((COVERAGE_WORKFLOW, None)); }
                        if opts.actionlint { list.push((ACTIONLINT_WORKFLOW, None)); }
                        if opts.healthcheck { list.push((HEALTHCHECK_WORKFLOW, None)); }
                        if matches.get_flag("release") { list.push((RELEASE_WORKFLOW, None)); }
                        if opts.matrix { list.push((MATRIX_WORKFLOW, None)); }
                        if opts.dependabot { list.push((DEPENDABOT_CONFIG, Some(".github"))); }
                        list
                    }
                    "gitlab" => vec![(".gitlab-ci.yml", None)],
                    "bitbucket" => vec![("bitbucket-pipelines.yml", None)],
                    "azure" => vec![("azure-pipelines.yml", None)],
                    "circleci" => vec![("config.yml", None)],
                    "woodpecker" => vec![(".woodpecker.yml", None)],
                    "buildkite" => vec![("pipeline.yml", None)],
                    _ => return Err(ForgeError::InvalidArgument(format!(
                        "unknown provider `{provider}` (available: {})",
                        available_providers().join(", ")
                    ))),
                };

                for (preset_name, dest_rel_override) in selected.drain(..) {
                    let file = provider_dir
                        .get_file(format!("{provider}/{preset_name}"))
                        .ok_or_else(|| ForgeError::Template(format!("missing preset file {provider}/{preset_name}")))?;
                    let contents = file
                        .contents_utf8()
                        .ok_or_else(|| ForgeError::Template(format!("preset {preset_name} is not UTF-8")))?;
                    let dest_rel = dest_rel_override.unwrap_or(output_dir(provider));
                    let out_path = dir.join(dest_rel).join(preset_name);
                    let rendered = render_str(contents, &{
                        let mut vars = Vars::new();
                        vars.insert("project_name".into(), name.to_string());
                        vars.insert("crate_name".into(), name.replace('-', "_"));
                        vars.insert("msrv".into(), opts.msrv.clone().unwrap_or_else(|| DEFAULT_MSRV.to_string()));
                        vars.insert("max_size".into(), max_size.to_string());
                        vars
                    });
                    if out_path.exists() {
                        let existing = std::fs::read_to_string(&out_path)
                            .map_err(ForgeError::io(format!("reading {}", out_path.display())))?;
                        if existing == rendered {
                            continue;
                        }
                        print_diff(&out_path, &rendered)?;
                    } else {
                        let parent = out_path.parent().unwrap_or(&dir);
                        std::fs::create_dir_all(parent).map_err(ForgeError::io(format!("creating {}", parent.display())))?;
                        print_diff(&out_path, &rendered)?;
                    }
                }
            }
            return Ok(());
        }

        // ── generate ───────────────────────────────────────────────────────
        let release = matches.get_flag("release");
        let force = matches.get_flag("force");

        if ctx.json {
            let mut results = Vec::new();
            for provider in &providers {
                let written = generate(&dir, provider, &name, opts.deploy, release, &opts, force)?;
                results.push(serde_json::json!({
                    "provider": provider,
                    "project_name": name,
                    "written_files": written,
                }));
            }
            let report = if results.len() == 1 {
                results.remove(0)
            } else {
                serde_json::json!(results)
            };
            println!("{}", serde_json::to_string_pretty(&report).unwrap());
        } else {
            for provider in &providers {
                let written = generate(&dir, provider, &name, opts.deploy, release, &opts, force)?;
                if !ctx.quiet {
                    print!("{}", format_report(provider, &name, &written, release, &opts));
                }
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn base_opts() -> GenerateOptions {
        GenerateOptions::default()
    }

    #[allow(dead_code)]
    fn deploy_opts() -> GenerateOptions {
        GenerateOptions {
            deploy: true,
            ..Default::default()
        }
    }

    #[test]
    fn coverage_defaults_to_false() {
        assert!(!GenerateOptions::default().coverage);
    }

    #[test]
    fn coverage_flag_is_parsed() {
        let matches = CiPresetsPlugin
            .command()
            .try_get_matches_from(["ci-init", "--coverage"])
            .unwrap();
        assert!(matches.get_flag("coverage"));
    }

    #[test]
    fn actionlint_and_max_size_flags_are_parsed() {
        let matches = CiPresetsPlugin
            .command()
            .try_get_matches_from(["ci-init", "--actionlint", "--max-size", "65536"])
            .unwrap();
        assert!(matches.get_flag("actionlint"));
        assert_eq!(matches.get_one::<u64>("max-size"), Some(&65_536));
    }

    #[test]
    fn github_preset_generates_coverage_only_when_enabled() {
        let default_dir = tempfile::tempdir().unwrap();
        let default_written = generate(
            default_dir.path(),
            "github",
            "my-contract",
            false,
            false,
            &base_opts(),
            false,
        )
        .unwrap();
        assert_eq!(
            default_written,
            vec![
                ".github/workflows/build-test.yml",
                ".github/workflows/contract-size.yml"
            ]
        );
        assert!(!default_dir
            .path()
            .join(".github/workflows/coverage.yml")
            .exists());

        let coverage_dir = tempfile::tempdir().unwrap();
        let coverage_written = generate(
            coverage_dir.path(),
            "github",
            "my-contract",
            false,
            false,
            &GenerateOptions {
                coverage: true,
                ..Default::default()
            },
            false,
        )
        .unwrap();
        assert!(coverage_written
            .iter()
            .any(|p| p == ".github/workflows/coverage.yml"));
        let contents =
            std::fs::read_to_string(coverage_dir.path().join(".github/workflows/coverage.yml"))
                .unwrap();
        assert!(contents.contains("codecov/codecov-action@v4"));
        assert!(contents.contains("cargo llvm-cov"));
    }

    #[test]
    fn stale_flag_is_parsed() {
        let matches = CiPresetsPlugin
            .command()
            .try_get_matches_from(["ci-init", "--stale"])
            .unwrap();
        assert!(matches.get_flag("stale"));
    }

    #[test]
    fn available_providers_includes_github_gitlab_circleci_azure() {
        let providers = available_providers();
        assert!(providers.contains(&"github"));
        assert!(providers.contains(&"gitlab"));
        assert!(providers.contains(&"circleci"));
        assert!(providers.contains(&"bitbucket"));
        assert!(providers.contains(&"azure"));
        assert!(providers.contains(&"woodpecker"));
        assert!(providers.contains(&"buildkite"));
    }

    #[test]
    fn writes_azure_preset() {
        let dir = tempfile::tempdir().unwrap();
        let written = generate(
            dir.path(),
            "azure",
            "my-contract",
            false,
            false,
            &base_opts(),
            false,
        )
        .unwrap();
        assert_eq!(written, vec!["azure-pipelines.yml"]);
        let contents = std::fs::read_to_string(dir.path().join("azure-pipelines.yml")).unwrap();
        assert!(contents.contains("CI/CD configuration for my-contract"));
        assert!(contents.contains("cargo test"));
        assert!(contents.contains("cargo build --target wasm32v1-none --release"));
        assert!(!contents.contains("{{project_name}}"));
    }

    #[test]
    fn writes_bitbucket_preset() {
        let dir = tempfile::tempdir().unwrap();
        let written = generate(
            dir.path(),
            "bitbucket",
            "my-contract",
            false,
            false,
            &base_opts(),
            false,
        )
        .unwrap();
        assert_eq!(written, vec!["bitbucket-pipelines.yml"]);
    }

    #[test]
    fn writes_woodpecker_preset() {
        let dir = tempfile::tempdir().unwrap();
        let written = generate(
            dir.path(),
            "woodpecker",
            "my-contract",
            false,
            false,
            &base_opts(),
            false,
        )
        .unwrap();
        assert_eq!(written, vec![".woodpecker.yml"]);
        let contents = std::fs::read_to_string(dir.path().join(".woodpecker.yml")).unwrap();
        assert!(contents.contains("my-contract"));
        assert!(contents.contains("cargo test"));
        assert!(contents.contains("cargo build --target wasm32v1-none --release"));
        assert!(contents.contains("cargo clippy --all-targets -- -D warnings"));
        assert!(!contents.contains("{{project_name}}"));
    }

    #[test]
    fn writes_buildkite_preset() {
        let dir = tempfile::tempdir().unwrap();
        let written = generate(
            dir.path(),
            "buildkite",
            "my-contract",
            false,
            false,
            &base_opts(),
            false,
        )
        .unwrap();
        assert_eq!(written, vec![".buildkite/pipeline.yml"]);
        let contents = std::fs::read_to_string(dir.path().join(".buildkite/pipeline.yml")).unwrap();
        assert!(contents.contains("my-contract"));
        assert!(contents.contains("cargo test"));
        assert!(contents.contains("cargo build --target wasm32v1-none --release"));
        assert!(contents.contains("MAX_WASM_BYTES"));
        assert!(!contents.contains("{{project_name}}"));
        assert!(!contents.contains("{{max_size}}"));
    }

    /// Structural validation against Buildkite's pipeline schema
    /// (https://buildkite.com/docs/pipelines/configure/step-types/command-step):
    /// a pipeline is a mapping with a `steps` sequence, and every command step
    /// (one with a `command`/`commands` key, as opposed to `wait`/`block`/
    /// `input`/`trigger`/`group`) has the shapes those keys require.
    fn assert_valid_buildkite_pipeline(yaml: &str) {
        let doc: serde_yaml::Value = serde_yaml::from_str(yaml).expect("valid YAML");
        let root = doc.as_mapping().expect("pipeline root must be a mapping");

        if let Some(env) = root.get("env") {
            let env = env.as_mapping().expect("`env` must be a mapping");
            for (key, _) in env {
                assert!(key.as_str().is_some(), "`env` keys must be strings");
            }
        }

        let steps = root
            .get("steps")
            .expect("pipeline must have a top-level `steps` key")
            .as_sequence()
            .expect("`steps` must be a sequence");
        assert!(!steps.is_empty(), "`steps` must not be empty");

        for step in steps {
            let step = step.as_mapping().expect("each step must be a mapping");

            if let Some(label) = step.get("label") {
                assert!(label.as_str().is_some(), "`label` must be a string");
            }
            if let Some(key) = step.get("key") {
                assert!(key.as_str().is_some(), "`key` must be a string");
            }
            if let Some(depends_on) = step.get("depends_on") {
                assert!(
                    depends_on.as_str().is_some() || depends_on.as_sequence().is_some(),
                    "`depends_on` must be a string or a sequence of strings"
                );
            }

            let command = step.get("command").or_else(|| step.get("commands"));
            if let Some(command) = command {
                let is_valid = command.as_str().is_some()
                    || command
                        .as_sequence()
                        .is_some_and(|seq| seq.iter().all(|c| c.as_str().is_some()));
                assert!(
                    is_valid,
                    "`command`/`commands` must be a string or a sequence of strings, got {command:?}"
                );
            } else {
                // Not a command step — one of `wait`/`block`/`input`/`trigger`/`group`,
                // which this preset never emits, but a real pipeline may mix in.
                assert!(
                    step.get("wait").is_some()
                        || step.get("block").is_some()
                        || step.get("input").is_some()
                        || step.get("trigger").is_some()
                        || step.get("group").is_some(),
                    "step has neither `command`/`commands` nor a recognised non-command step key: {step:?}"
                );
                continue;
            }

            if let Some(plugins) = step.get("plugins") {
                let plugins = plugins.as_sequence().expect("`plugins` must be a sequence");
                for plugin in plugins {
                    let plugin = plugin
                        .as_mapping()
                        .expect("each plugin entry must be a mapping");
                    assert_eq!(
                        plugin.len(),
                        1,
                        "each plugin entry must have exactly one key (the plugin reference)"
                    );
                }
            }
        }
    }

    #[test]
    fn buildkite_pipeline_validates_against_schema() {
        let dir = tempfile::tempdir().unwrap();
        generate(
            dir.path(),
            "buildkite",
            "my-contract",
            false,
            false,
            &base_opts(),
            false,
        )
        .unwrap();
        let contents = std::fs::read_to_string(dir.path().join(".buildkite/pipeline.yml")).unwrap();
        assert_valid_buildkite_pipeline(&contents);

        // The steps this preset is required to emit (#240): build, test and
        // contract-size, mirroring the GitHub build-test preset's jobs.
        assert!(contents.contains("build & test"));
        assert!(contents.contains("contract size"));
    }

    #[test]
    fn github_release_preset_is_emitted_when_requested() {
        let dir = tempfile::tempdir().unwrap();
        let written = generate(dir.path(), "github", "my-contract", false, true, &base_opts(), false).unwrap();
        assert!(written.iter().any(|path| path == ".github/workflows/release.yml"));
        let contents = std::fs::read_to_string(dir.path().join(".github/workflows/release.yml")).unwrap();
        assert!(contents.contains("cargo build --target wasm32v1-none --release --locked"));
        assert!(contents.contains("softprops/action-gh-release@v2"));
        assert!(contents.contains("v*.*.*"));
    }

    #[test]
    fn ci_init_path_flag_is_honored() {
        let matches = CiPresetsPlugin
            .command()
            .try_get_matches_from(["ci-init", "--path", "../contracts/demo"])
            .unwrap();
        let dir = matches
            .get_one::<String>("path")
            .map(|path| std::path::PathBuf::from(path))
            .unwrap();
        assert_eq!(dir, std::path::PathBuf::from("../contracts/demo"));
    }

    // ── parse_providers tests ───────────────────────────────────────────────

    #[test]
    fn parse_providers_single() {
        assert_eq!(parse_providers("github").unwrap(), vec!["github"]);
    }

    #[test]
    fn parse_providers_two_providers() {
        assert_eq!(
            parse_providers("github,gitlab").unwrap(),
            vec!["github", "gitlab"]
        );
    }

    #[test]
    fn parse_providers_ignores_whitespace() {
        assert_eq!(
            parse_providers(" github , gitlab ").unwrap(),
            vec!["github", "gitlab"]
        );
    }

    #[test]
    fn parse_providers_deduplicates() {
        assert_eq!(
            parse_providers("github,github").unwrap(),
            vec!["github"]
        );
    }

    #[test]
    fn parse_providers_rejects_unknown() {
        let err = parse_providers("github,jenkins").unwrap_err().to_string();
        assert!(err.contains("jenkins"), "error should name the bad provider: {err}");
    }

    #[test]
    fn parse_providers_rejects_empty_string() {
        assert!(parse_providers("").is_err());
        assert!(parse_providers(",,,").is_err());
    }

    /// Two providers in a single invocation each produce their own files and
    /// neither tramples the other's output directory.
    #[test]
    fn generate_two_providers_in_one_invocation() {
        let dir = tempfile::tempdir().unwrap();

        // github
        let github_written = generate(
            dir.path(),
            "github",
            "my-contract",
            false,
            false,
            &base_opts(),
            false,
        )
        .unwrap();
        // gitlab
        let gitlab_written = generate(
            dir.path(),
            "gitlab",
            "my-contract",
            false,
            false,
            &base_opts(),
            false,
        )
        .unwrap();

        // Each provider wrote at least one file.
        assert!(!github_written.is_empty(), "github should write files");
        assert!(!gitlab_written.is_empty(), "gitlab should write files");

        // The two sets of files are entirely disjoint.
        for gh in &github_written {
            assert!(
                !gitlab_written.contains(gh),
                "file {gh} appears in both provider outputs"
            );
        }

        // The files actually exist on disk.
        for path in github_written.iter().chain(gitlab_written.iter()) {
            assert!(
                dir.path().join(path).exists(),
                "{path} should exist on disk"
            );
        }

        // GitHub writes into .github/workflows/; GitLab writes at the root.
        assert!(github_written
            .iter()
            .all(|p| p.starts_with(".github/workflows/")));
        assert!(gitlab_written
            .iter()
            .all(|p| p == ".gitlab-ci.yml"));
    }

    // ── --remove tests ─────────────────────────────────────────────────────

    /// `--remove` deletes every file that the preset generated.
    #[test]
    fn remove_deletes_generated_files() {
        let dir = tempfile::tempdir().unwrap();
        // Generate the base github preset first.
        let written = generate(
            dir.path(),
            "github",
            "my-contract",
            false,
            false,
            &base_opts(),
            false,
        )
        .unwrap();
        // Confirm the files are on disk.
        for rel in &written {
            assert!(dir.path().join(rel).exists(), "{rel} should exist after generate");
        }

        // Now remove them.
        let removed = remove(dir.path(), "github", false).unwrap();
        assert_eq!(removed.len(), written.len(), "all generated files should be removed");
        for rel in &written {
            assert!(
                !dir.path().join(rel).exists(),
                "{rel} should be gone after remove"
            );
        }
    }

    /// `--remove` refuses to delete a file that lacks the forge marker (i.e.
    /// was not written by soroban-forge) unless `--force` is passed.
    #[test]
    fn remove_refuses_non_forge_file_without_force() {
        let dir = tempfile::tempdir().unwrap();
        // Create the directory structure and drop in a hand-written workflow.
        let wf_dir = dir.path().join(".github/workflows");
        std::fs::create_dir_all(&wf_dir).unwrap();
        std::fs::write(
            wf_dir.join("build-test.yml"),
            "name: my-hand-crafted-workflow\non:\n  push:\n",
        )
        .unwrap();

        // Without --force the remove should error.
        let result = remove(dir.path(), "github", false);
        assert!(
            result.is_err(),
            "remove should refuse a non-forge file without --force"
        );
        let err = result.unwrap_err().to_string();
        assert!(
            err.contains(FORGE_MARKER),
            "error message should mention the marker; got: {err}"
        );

        // The file must still be on disk.
        assert!(wf_dir.join("build-test.yml").exists());
    }

    /// `--force` allows removing a file even when it lacks the forge marker.
    #[test]
    fn remove_force_deletes_non_forge_file() {
        let dir = tempfile::tempdir().unwrap();
        let wf_dir = dir.path().join(".github/workflows");
        std::fs::create_dir_all(&wf_dir).unwrap();
        std::fs::write(
            wf_dir.join("build-test.yml"),
            "name: my-hand-crafted-workflow\non:\n  push:\n",
        )
        .unwrap();

        let removed = remove(dir.path(), "github", true).unwrap();
        assert_eq!(removed.len(), 1, "one file should be removed");
        assert!(removed[0].contains("build-test.yml"));
        assert!(!wf_dir.join("build-test.yml").exists());
    }

    /// The `--remove` flag is accepted by the clap command definition.
    #[test]
    fn remove_flag_is_parsed() {
        let matches = CiPresetsPlugin
            .command()
            .try_get_matches_from(["ci-init", "--provider", "github", "--remove"])
            .unwrap();
        assert!(matches.get_flag("remove"));
    }
}
