//! Subscription — a recurring payment charged once per elapsed interval.
//!
//! A merchant configures one plan (token, amount, interval). Subscribers opt
//! in and the merchant pulls the fee once per interval:
//!
//! * **Allowance, not custody** — the contract never holds subscriber funds.
//!   The subscriber `approve`s this contract on the token for as many periods
//!   as they want to pre-pay, and `charge` moves one period's amount straight
//!   to the merchant with `transfer_from`. Revoking the allowance is enough to
//!   stop payments even without calling `cancel`.
//! * **One charge per interval** — the due date advances by exactly `interval`
//!   per charge, so a merchant calling twice in a row is rejected and a late
//!   charge does not silently skip a period.
//! * **Cancel any time** — the subscriber deactivates their subscription;
//!   further charges are rejected.
//!
//! Generated by [soroban-forge](https://github.com/soroban-forge-labs/soroban-forge).

#![no_std]

use soroban_sdk::{contract, contractimpl, contracttype, token, Address, Env};

#[contracttype]
pub enum DataKey {
    Merchant,
    Token,
    Amount,
    Interval,
    /// One subscriber's state.
    Sub(Address),
}

/// Per-subscriber state.
#[contracttype]
#[derive(Clone)]
pub struct Subscription {
    /// Whether charges are still allowed.
    pub active: bool,
    /// Ledger timestamp the next charge becomes due at.
    pub next_charge: u64,
    /// How many periods have been charged so far.
    pub charges: u32,
}

#[contract]
pub struct SubscriptionContract;

#[contractimpl]
impl SubscriptionContract {
    /// Configure the single plan this contract bills.
    ///
    /// * `merchant` — address that receives the payments and may call `charge`
    /// * `token`    — contract address of the SEP-41 token to charge in
    /// * `amount`   — amount charged per interval
    /// * `interval` — seconds between charges
    pub fn initialize(env: Env, merchant: Address, token: Address, amount: i128, interval: u64) {
        merchant.require_auth();
        if amount <= 0 {
            panic!("amount must be positive");
        }
        if interval == 0 {
            panic!("interval must be positive");
        }
        env.storage().instance().set(&DataKey::Merchant, &merchant);
        env.storage().instance().set(&DataKey::Token, &token);
        env.storage().instance().set(&DataKey::Amount, &amount);
        env.storage().instance().set(&DataKey::Interval, &interval);
    }

    /// Subscribe `subscriber` and charge the first period immediately.
    ///
    /// The subscriber must already have approved this contract on the token
    /// for at least one period's `amount`.
    pub fn subscribe(env: Env, subscriber: Address) {
        subscriber.require_auth();

        if let Some(existing) = Self::subscription_of(&env, &subscriber) {
            if existing.active {
                panic!("already subscribed");
            }
        }

        let now = env.ledger().timestamp();
        let interval = Self::interval(env.clone());

        // Pay for the first period up front, then the next one is due after a
        // full interval.
        Self::pull_payment(&env, &subscriber);
        env.storage().instance().set(
            &DataKey::Sub(subscriber),
            &Subscription {
                active: true,
                next_charge: now + interval,
                charges: 1,
            },
        );
    }

    /// Charge `subscriber` for the period that has come due.
    ///
    /// Callable by the merchant once per interval. Panics when the
    /// subscription is inactive or the interval has not elapsed yet.
    pub fn charge(env: Env, subscriber: Address) -> i128 {
        Self::merchant(env.clone()).require_auth();

        let mut sub =
            Self::subscription_of(&env, &subscriber).unwrap_or_else(|| panic!("not subscribed"));
        if !sub.active {
            panic!("subscription is not active");
        }
        if env.ledger().timestamp() < sub.next_charge {
            panic!("interval has not elapsed");
        }

        let amount = Self::pull_payment(&env, &subscriber);

        // Advance by exactly one interval so a late charge does not skip a
        // period, and two charges in a row are impossible.
        sub.next_charge += Self::interval(env.clone());
        sub.charges += 1;
        env.storage()
            .instance()
            .set(&DataKey::Sub(subscriber), &sub);

        amount
    }

    /// Cancel `subscriber`'s subscription. Further charges are rejected.
    pub fn cancel(env: Env, subscriber: Address) {
        subscriber.require_auth();

        let mut sub =
            Self::subscription_of(&env, &subscriber).unwrap_or_else(|| panic!("not subscribed"));
        if !sub.active {
            panic!("subscription is not active");
        }
        sub.active = false;
        env.storage()
            .instance()
            .set(&DataKey::Sub(subscriber), &sub);
    }

    /// Whether `subscriber` has an active subscription.
    pub fn is_active(env: Env, subscriber: Address) -> bool {
        Self::subscription_of(&env, &subscriber)
            .map(|sub| sub.active)
            .unwrap_or(false)
    }

    /// `subscriber`'s state. Panics when they never subscribed.
    pub fn subscription(env: Env, subscriber: Address) -> Subscription {
        Self::subscription_of(&env, &subscriber).unwrap_or_else(|| panic!("not subscribed"))
    }

    /// Whether a charge would succeed right now.
    pub fn is_due(env: Env, subscriber: Address) -> bool {
        match Self::subscription_of(&env, &subscriber) {
            Some(sub) => sub.active && env.ledger().timestamp() >= sub.next_charge,
            None => false,
        }
    }

    /// The configured merchant.
    pub fn merchant(env: Env) -> Address {
        env.storage().instance().get(&DataKey::Merchant).unwrap()
    }

    /// Amount charged per interval.
    pub fn amount(env: Env) -> i128 {
        env.storage().instance().get(&DataKey::Amount).unwrap()
    }

    /// Seconds between charges.
    pub fn interval(env: Env) -> u64 {
        env.storage().instance().get(&DataKey::Interval).unwrap()
    }

    /// Move one period's amount from `subscriber` to the merchant using the
    /// allowance the subscriber granted this contract.
    fn pull_payment(env: &Env, subscriber: &Address) -> i128 {
        let amount = Self::amount(env.clone());
        let merchant = Self::merchant(env.clone());
        let token: Address = env.storage().instance().get(&DataKey::Token).unwrap();
        token::Client::new(env, &token).transfer_from(
            &env.current_contract_address(),
            subscriber,
            &merchant,
            &amount,
        );
        amount
    }

    fn subscription_of(env: &Env, subscriber: &Address) -> Option<Subscription> {
        env.storage()
            .instance()
            .get(&DataKey::Sub(subscriber.clone()))
    }
}

#[cfg(test)]
mod test;
