//! An oracle-consumer contract: reads the latest price for a configured
//! asset from an external oracle contract and uses it to convert amounts.
//!
//! The oracle interface (`lastprice`) matches the shape published by
//! [Reflector](https://reflector.network/), a common Stellar price oracle,
//! so this contract can be pointed at a real deployed Reflector instance —
//! or, as in the tests, at a small mock oracle contract.
//!
//! Generated by [soroban-forge](https://github.com/soroban-forge-labs/soroban-forge).

#![no_std]

use soroban_sdk::{
    contract, contractclient, contracterror, contractimpl, contracttype, panic_with_error,
    Address, Env, Symbol,
};

/// A single price observation, matching the shape returned by Reflector's
/// `lastprice`.
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PriceData {
    pub price: i128,
    pub timestamp: u64,
}

/// The external oracle interface this contract consumes.
#[contractclient(name = "OracleClient")]
pub trait OracleInterface {
    fn lastprice(env: Env, asset: Symbol) -> Option<PriceData>;
}

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum Error {
    PriceUnavailable = 1,
}

#[contracttype]
pub enum DataKey {
    Oracle,
    Asset,
    PriceDecimals,
}

#[contract]
pub struct OracleConsumerContract;

#[contractimpl]
impl OracleConsumerContract {
    /// Configure which oracle contract and asset to read prices for.
    ///
    /// * `oracle` — contract address implementing `lastprice`
    /// * `asset` — the asset symbol to price (e.g. `XLM`)
    /// * `price_decimals` — number of decimals the oracle's price uses
    pub fn __constructor(env: Env, oracle: Address, asset: Symbol, price_decimals: u32) {
        env.storage().instance().set(&DataKey::Oracle, &oracle);
        env.storage().instance().set(&DataKey::Asset, &asset);
        env.storage()
            .instance()
            .set(&DataKey::PriceDecimals, &price_decimals);
    }

    /// Fetch the latest price for the configured asset from the oracle.
    /// Panics if the oracle has no price data available.
    pub fn get_price(env: Env) -> i128 {
        let oracle: Address = env.storage().instance().get(&DataKey::Oracle).unwrap();
        let asset: Symbol = env.storage().instance().get(&DataKey::Asset).unwrap();

        let client = OracleClient::new(&env, &oracle);
        match client.lastprice(&asset) {
            Some(data) => data.price,
            None => panic_with_error!(&env, Error::PriceUnavailable),
        }
    }

    /// Convert `amount` (in the base asset's smallest unit) into its value
    /// denominated in the oracle's quote asset, using the latest price.
    pub fn convert(env: Env, amount: i128) -> i128 {
        let price = Self::get_price(env.clone());
        let decimals: u32 = env
            .storage()
            .instance()
            .get(&DataKey::PriceDecimals)
            .unwrap();
        let scale = 10i128.pow(decimals);
        (amount * price) / scale
    }
}

#[cfg(test)]
mod test;
