//! Test fixtures generated by `soroban-forge test-init`.
//!
//! Extend freely — this file is only written once and never overwritten
//! (unless you pass `--force`).
#![allow(dead_code)]

use soroban_sdk::testutils::{Address as _, Ledger};
use soroban_sdk::token::{StellarAssetClient, TokenClient};
use soroban_sdk::{Address, Env};

/// An `Env` with all auths mocked — the convenient default for unit tests.
pub fn test_env() -> Env {
    let env = Env::default();
    env.mock_all_auths();
    env
}

/// A fresh test account address.
pub fn new_account(env: &Env) -> Address {
    Address::generate(env)
}

/// Advance the ledger timestamp by `secs` seconds.
pub fn advance_time(env: &Env, secs: u64) {
    env.ledger().with_mut(|li| li.timestamp += secs);
}

/// Register a Stellar Asset Contract to use as a test token.
/// Returns `(token_address, token_client, admin_client)`; use the admin
/// client to `mint` balances to test accounts.
pub fn create_token<'a>(
    env: &'a Env,
    admin: &Address,
) -> (Address, TokenClient<'a>, StellarAssetClient<'a>) {
    let sac = env.register_stellar_asset_contract_v2(admin.clone());
    let address = sac.address();
    (
        address.clone(),
        TokenClient::new(env, &address),
        StellarAssetClient::new(env, &address),
    )
}

/// Mint `amount` of `token` (a Stellar Asset Contract) to `to`.
pub fn fund(env: &Env, token: &Address, to: &Address, amount: i128) {
    StellarAssetClient::new(env, token).mint(to, &amount);
}

/// Snapshot assertion: compares `value`'s `Debug` output against
/// `tests/snapshots/<name>.snap`.
///
/// - First run (or `FORGE_UPDATE_SNAPSHOTS=1`): writes the snapshot and passes.
/// - Later runs: fails with a diff hint when output changed.
pub fn assert_snapshot(name: &str, value: &dyn core::fmt::Debug) {
    let rendered = format!("{value:#?}\n");
    let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/snapshots");
    let path = dir.join(format!("{name}.snap"));
    if std::env::var("FORGE_UPDATE_SNAPSHOTS").is_ok() || !path.exists() {
        std::fs::create_dir_all(&dir).expect("create snapshot dir");
        std::fs::write(&path, &rendered).expect("write snapshot");
        return;
    }
    let expected = std::fs::read_to_string(&path).expect("read snapshot");
    assert_eq!(
        expected, rendered,
        "snapshot `{name}` changed — rerun with FORGE_UPDATE_SNAPSHOTS=1 to accept"
    );
}
