//! # soroban-forge-testgen
//!
//! `soroban-forge test-init` — generates a test harness for an existing
//! Soroban contract project:
//!
//! - `tests/common/mod.rs` — fixture helpers (env with mocked auths, test
//!   accounts, token setup, ledger-time control) and a file-based snapshot
//!   assertion helper.
//! - `tests/forge_smoke.rs` — a smoke test that registers the detected
//!   `#[contract]` type and constructs its client.
//!
//! The generator inspects `src/lib.rs` to find the contract type. When the
//! contract declares a `__constructor`, the smoke test is emitted `#[ignore]`d
//! with a TODO, because constructor arguments cannot be guessed.

pub mod detect;

use std::path::Path;

use clap::{Arg, ArgAction, ArgMatches, Command};
use soroban_forge_core::render::{render_str, Vars};
use soroban_forge_core::{ForgeContext, ForgeError, ForgePlugin, Result};

pub use detect::{inspect, ContractInfo};

/// Contents of the generated `tests/common/mod.rs`.
pub const FIXTURES_RS: &str = r#"//! Test fixtures generated by `soroban-forge test-init`.
//!
//! Extend freely — this file is only written once and never overwritten
//! (unless you pass `--force`).
#![allow(dead_code)] // generated fixtures

use soroban_sdk::testutils::{Address as _, Ledger};
use soroban_sdk::token::{StellarAssetClient, TokenClient};
use soroban_sdk::{Address, Env};

/// An `Env` with all auths mocked — the convenient default for unit tests.
pub fn test_env() -> Env {
    let env = Env::default();
    env.mock_all_auths();
    env
}

/// A fresh test account address.
pub fn new_account(env: &Env) -> Address {
    Address::generate(env)
}

/// Advance the ledger timestamp by `secs` seconds.
pub fn advance_time(env: &Env, secs: u64) {
    env.ledger().with_mut(|li| li.timestamp += secs);
}

/// Register a Stellar Asset Contract to use as a test token.
/// Returns `(token_address, token_client, admin_client)`; use the admin
/// client to `mint` balances to test accounts.
pub fn create_token<'a>(
    env: &'a Env,
    admin: &Address,
) -> (Address, TokenClient<'a>, StellarAssetClient<'a>) {
    let sac = env.register_stellar_asset_contract_v2(admin.clone());
    let address = sac.address();
    (
        address.clone(),
        TokenClient::new(env, &address),
        StellarAssetClient::new(env, &address),
    )
}

/// Mint `amount` of `token` (a Stellar Asset Contract) to `to`.
pub fn fund(env: &Env, token: &Address, to: &Address, amount: i128) {
    StellarAssetClient::new(env, token).mint(to, &amount);
}

/// Snapshot assertion: compares `value`'s `Debug` output against
/// `tests/snapshots/<name>.snap`.
///
/// - First run (or `FORGE_UPDATE_SNAPSHOTS=1`): writes the snapshot and passes.
/// - Later runs: fails with a diff hint when output changed.
pub fn assert_snapshot(name: &str, value: &dyn core::fmt::Debug) {
    let rendered = format!("{value:#?}\n");
    let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/snapshots");
    let path = dir.join(format!("{name}.snap"));
    if std::env::var("FORGE_UPDATE_SNAPSHOTS").is_ok() || !path.exists() {
        std::fs::create_dir_all(&dir).expect("create snapshot dir");
        std::fs::write(&path, &rendered).expect("write snapshot");
        return;
    }
    let expected = std::fs::read_to_string(&path).expect("read snapshot");
    assert_eq!(
        expected, rendered,
        "snapshot `{name}` changed — rerun with FORGE_UPDATE_SNAPSHOTS=1 to accept"
    );
}
"#;

/// Template for the generated smoke test (contract without constructor).
pub const SMOKE_TEST_RS: &str = r#"//! Generated by `soroban-forge test-init`. Grow it into your real test suite.

mod common;

use {{crate_name}}::{ {{contract_type}}, {{contract_type}}Client };

#[test]
fn contract_registers_and_client_constructs() {
    let env = common::test_env();
    let contract_id = env.register({{contract_type}}, ());
    let _client = {{contract_type}}Client::new(&env, &contract_id);
}
"#;

/// Template for the generated smoke test when the contract declares a
/// `__constructor` — arguments can't be guessed, so it ships `#[ignore]`d.
pub const SMOKE_TEST_CONSTRUCTOR_RS: &str = r#"//! Generated by `soroban-forge test-init`. Grow it into your real test suite.

mod common;

#[allow(unused_imports)]
use {{crate_name}}::{ {{contract_type}}, {{contract_type}}Client };

#[test]
#[ignore = "this contract has a __constructor — fill in its arguments below, then remove this ignore"]
fn contract_registers_and_client_constructs() {
    let env = common::test_env();
    // TODO: provide the constructor arguments, e.g.:
    // let contract_id = env.register({{contract_type}}, (arg1, arg2));
    // let _client = {{contract_type}}Client::new(&env, &contract_id);
    let _ = env;
}
"#;

/// Generate the harness into `dir`. Public API behind `test-init`.
/// Returns the list of files written (relative to `dir`).
pub fn generate(dir: &Path, force: bool) -> Result<(ContractInfo, Vec<&'static str>)> {
    let info = detect::inspect(dir)?;

    let mut vars = Vars::new();
    vars.insert("crate_name".into(), info.crate_name.clone());
    vars.insert("contract_type".into(), info.contract_type.clone());

    let smoke = if info.has_constructor {
        SMOKE_TEST_CONSTRUCTOR_RS
    } else {
        SMOKE_TEST_RS
    };

    let files: [(&'static str, String); 2] = [
        ("tests/common/mod.rs", FIXTURES_RS.to_string()),
        ("tests/forge_smoke.rs", render_str(smoke, &vars)),
    ];

    let mut written = Vec::new();
    for (rel, contents) in files {
        let path = dir.join(rel);
        if path.exists() && !force {
            return Err(ForgeError::AlreadyExists(path));
        }
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(ForgeError::io(format!("creating {}", parent.display())))?;
        }
        std::fs::write(&path, contents)
            .map_err(ForgeError::io(format!("writing {}", path.display())))?;
        written.push(rel);
    }
    Ok((info, written))
}

/// Render the report for a generated test harness.
pub fn format_report(info: &ContractInfo, written: &[&str]) -> String {
    let mut out = format!(
        "generated test harness for contract `{}` (crate `{}`):\n",
        info.contract_type, info.crate_name
    );
    for rel in written {
        out.push_str(&format!("  {rel}\n"));
    }
    if !info.has_testutils {
        out.push_str(
            "\nwarning: dev-dependencies do not enable soroban-sdk's `testutils` feature.\n",
        );
        out.push_str("add this to Cargo.toml or the generated tests will not compile:\n\n");
        out.push_str("  [dev-dependencies]\n");
        out.push_str("  soroban-sdk = { version = \"*\", features = [\"testutils\"] }\n");
    }
    if info.has_constructor {
        out.push_str(&format!(
            "\nnote: `{}` has a __constructor, so the smoke test is #[ignore]d until you fill in its arguments.\n",
            info.contract_type
        ));
    }
    out.push_str("\nrun them with: cargo test\n");
    out
}

/// The `test-init` subcommand.
pub struct TestgenPlugin;

impl ForgePlugin for TestgenPlugin {
    fn name(&self) -> &'static str {
        "test-init"
    }

    fn command(&self) -> Command {
        Command::new("test-init")
            .about("Generate a test harness (fixtures, smoke test, snapshot helper) for an existing contract")
            .arg(
                Arg::new("path")
                    .long("path")
                    .help("Contract project directory [default: current directory]"),
            )
            .arg(
                Arg::new("force")
                    .long("force")
                    .action(ArgAction::SetTrue)
                    .help("Overwrite previously generated files"),
            )
    }

    fn run(&self, matches: &ArgMatches, ctx: &ForgeContext) -> Result<()> {
        let dir = matches
            .get_one::<String>("path")
            .map(|p| ctx.cwd.join(p))
            .unwrap_or_else(|| ctx.cwd.clone());

        let (info, written) = generate(&dir, matches.get_flag("force"))?;

        if !ctx.quiet {
            print!("{}", format_report(&info, &written));
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use soroban_forge_scaffold as scaffold;

    fn hello_world_project(dir: &Path) {
        scaffold::generate(
            "hello-world",
            dir,
            &scaffold::project_vars("demo", "Test <t@example.com>"),
            false,
        )
        .unwrap();
    }

    fn contract_info(has_constructor: bool, has_testutils: bool) -> ContractInfo {
        ContractInfo {
            package_name: "demo".into(),
            crate_name: "demo".into(),
            contract_type: "DemoContract".into(),
            has_constructor,
            has_testutils,
        }
    }

    #[test]
    fn report_lists_generated_files() {
        let report = format_report(&contract_info(false, true), &["tests/a.rs", "tests/b.rs"]);
        assert!(report.contains("contract `DemoContract` (crate `demo`)"));
        assert!(report.contains("  tests/a.rs\n  tests/b.rs\n"));
    }

    #[test]
    fn report_explains_missing_testutils() {
        let report = format_report(&contract_info(false, false), &[]);
        assert!(report.contains("warning: dev-dependencies"));
        assert!(report.contains("features = [\"testutils\"]"));
    }

    #[test]
    fn report_explains_constructor_follow_up() {
        let report = format_report(&contract_info(true, true), &[]);
        assert!(report.contains("DemoContract` has a __constructor"));
        assert!(report.contains("#[ignore]d"));
    }

    #[test]
    fn generates_harness_for_hello_world_output() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("demo");
        hello_world_project(&dir);

        let (info, written) = generate(&dir, false).unwrap();
        assert_eq!(info.contract_type, "HelloContract");
        assert!(!info.has_constructor);
        assert!(info.has_testutils);
        assert_eq!(written, vec!["tests/common/mod.rs", "tests/forge_smoke.rs"]);

        let smoke = std::fs::read_to_string(dir.join("tests/forge_smoke.rs")).unwrap();
        assert!(smoke.contains("use demo::{ HelloContract, HelloContractClient };"));
        assert!(smoke.contains("env.register(HelloContract, ())"));
        assert!(!smoke.contains("{{"));
    }

    #[test]
    fn constructor_contract_gets_ignored_smoke_test() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("tok");
        scaffold::generate("token", &dir, &scaffold::project_vars("tok", "T"), false).unwrap();

        let (info, _) = generate(&dir, false).unwrap();
        assert!(info.has_constructor);
        let smoke = std::fs::read_to_string(dir.join("tests/forge_smoke.rs")).unwrap();
        assert!(smoke.contains("#[ignore"));
    }

    #[test]
    fn refuses_to_overwrite_without_force() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("demo");
        hello_world_project(&dir);

        generate(&dir, false).unwrap();
        assert!(matches!(
            generate(&dir, false),
            Err(ForgeError::AlreadyExists(_))
        ));
        generate(&dir, true).unwrap();
    }

    #[test]
    fn errors_outside_a_cargo_project() {
        let tmp = tempfile::tempdir().unwrap();
        assert!(generate(tmp.path(), false).is_err());
    }
}
