//! # soroban-forge-testgen
//!
//! `soroban-forge test-init` — generates a test harness for an existing
//! Soroban contract project:
//!
//! - `tests/common/mod.rs` — fixture helpers (env with mocked auths, test
//!   accounts, token setup, ledger-time control) and a file-based snapshot
//!   assertion helper.
//! - `tests/forge_smoke.rs` — smoke tests that register the detected
//!   `#[contract]` types and construct their clients.
//!
//! The generator inspects `src/lib.rs` to find the contract type. When the
//! contract declares a `__constructor`, the smoke test is emitted `#[ignore]`d
//! with a TODO, because constructor arguments cannot be guessed.

pub mod detect;

use std::path::Path;

use clap::{Arg, ArgAction, ArgMatches, Command};
use soroban_forge_core::render::{render_str, Vars};
use soroban_forge_core::{ForgeContext, ForgeError, ForgePlugin, Result};

pub use detect::{inspect, ContractInfo};

/// Contents of the generated `tests/common/mod.rs`.
pub const FIXTURES_RS: &str = r#"//! Test fixtures generated by `soroban-forge test-init`.
//!
//! Extend freely — this file is only written once and never overwritten
//! (unless you pass `--force`).
#![allow(dead_code)] // generated fixtures

use soroban_sdk::testutils::{Address as _, Ledger};
use soroban_sdk::token::{StellarAssetClient, TokenClient};
use soroban_sdk::{Address, Env};

/// An `Env` with all auths mocked — the convenient default for unit tests.
pub fn test_env() -> Env {
    let env = Env::default();
    env.mock_all_auths();
    env
}

/// A fresh test account address.
pub fn new_account(env: &Env) -> Address {
    Address::generate(env)
}

/// Advance the ledger timestamp by `secs` seconds.
pub fn advance_time(env: &Env, secs: u64) {
    env.ledger().with_mut(|li| li.timestamp += secs);
}

/// Register a Stellar Asset Contract to use as a test token.
/// Returns `(token_address, token_client, admin_client)`; use the admin
/// client to `mint` balances to test accounts.
pub fn create_token<'a>(
    env: &'a Env,
    admin: &Address,
) -> (Address, TokenClient<'a>, StellarAssetClient<'a>) {
    let sac = env.register_stellar_asset_contract_v2(admin.clone());
    let address = sac.address();
    (
        address.clone(),
        TokenClient::new(env, &address),
        StellarAssetClient::new(env, &address),
    )
}

/// Mint `amount` of `token` (a Stellar Asset Contract) to `to`.
pub fn fund(env: &Env, token: &Address, to: &Address, amount: i128) {
    StellarAssetClient::new(env, token).mint(to, &amount);
}

/// Snapshot assertion: compares `value`'s `Debug` output against
/// `tests/snapshots/<name>.snap`.
///
/// - First run (or `FORGE_UPDATE_SNAPSHOTS=1`): writes the snapshot and passes.
/// - Later runs: fails with a diff hint when output changed.
pub fn assert_snapshot(name: &str, value: &dyn core::fmt::Debug) {
    let rendered = format!("{value:#?}\n");
    let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/snapshots");
    let path = dir.join(format!("{name}.snap"));
    if std::env::var("FORGE_UPDATE_SNAPSHOTS").is_ok() || !path.exists() {
        std::fs::create_dir_all(&dir).expect("create snapshot dir");
        std::fs::write(&path, &rendered).expect("write snapshot");
        return;
    }
    let expected = std::fs::read_to_string(&path).expect("read snapshot");
    assert_eq!(
        expected, rendered,
        "snapshot `{name}` changed — rerun with FORGE_UPDATE_SNAPSHOTS=1 to accept"
    );
}
"#;

/// Template for the generated smoke test (contract with or without constructor).
pub const SMOKE_TEST_RS: &str = r#"//! Generated by `soroban-forge test-init`. Grow it into your real test suite.

mod common;
"#;

/// Per-contract smoke-test function (contract without `__constructor`).
/// Receives `contract_type` and `fn_name` variables.
pub const SMOKE_TEST_FN: &str = r#"
#[test]
fn {{fn_name}}_registers_and_client_constructs() {
    let env = common::test_env();
    let contract_id = env.register({{contract_type}}, {{contract_args}});
    let _client = {{contract_type}}Client::new(&env, &contract_id);
}
"#;

/// Convert `CamelCase` struct names to `snake_case` test function names.
pub fn to_snake_case(s: &str) -> String {
    let mut out = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.extend(c.to_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

/// Render the `tests/forge_smoke.rs` content for all `#[contract]` structs found.
pub fn build_smoke_test(info: &ContractInfo) -> String {
    let mut out = String::from(SMOKE_TEST_RS);

    let mut use_parts: Vec<String> = Vec::new();
    for ct in &info.contract_types {
        use_parts.push(ct.clone());
        use_parts.push(format!("{ct}Client"));
    }
    out.push_str(&format!(
        "use {}::{{ {} }};\n",
        info.crate_name,
        use_parts.join(", ")
    ));

    for ct in &info.contract_types {
        let mut vars = Vars::new();
        vars.insert("contract_type".into(), ct.clone());
        vars.insert("fn_name".into(), to_snake_case(ct));
        vars.insert("contract_args".into(), info.constructor_args.clone());

        out.push_str(&render_str(SMOKE_TEST_FN, &vars));
    }

    out
}

/// Generate the harness into `dir`. Public API behind `test-init`.
/// Returns the list of files written (relative to `dir`).
pub fn generate(dir: &Path, force: bool) -> Result<(ContractInfo, Vec<&'static str>)> {
    let info = detect::inspect(dir)?;

    let smoke = build_smoke_test(&info);

    let files: [(&'static str, String); 2] = [
        ("tests/common/mod.rs", FIXTURES_RS.to_string()),
        ("tests/forge_smoke.rs", smoke),
    ];

    let mut written = Vec::new();
    for (rel, contents) in files {
        let path = dir.join(rel);
        if path.exists() && !force {
            return Err(ForgeError::AlreadyExists(path));
        }
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(ForgeError::io(format!("creating {}", parent.display())))?;
        }
        std::fs::write(&path, contents)
            .map_err(ForgeError::io(format!("writing {}", path.display())))?;
        written.push(rel);
    }
    Ok((info, written))
}

/// Render the report for a generated test harness.
pub fn format_report(info: &ContractInfo, written: &[&str]) -> String {
    let contract_list = info.contract_types.join(", ");
    let s = if info.contract_types.len() == 1 {
        ""
    } else {
        "s"
    };
    let mut out = format!(
        "generated test harness for contract{s} `{contract_list}` (crate `{}`):\n",
        info.crate_name
    );
    for rel in written {
        out.push_str(&format!("  {rel}\n"));
    }
    if !info.has_testutils {
        out.push_str(
            "\nwarning: dev-dependencies do not enable soroban-sdk's `testutils` feature.\n",
        );
        out.push_str("add this to Cargo.toml or the generated tests will not compile:\n\n");
        out.push_str("  [dev-dependencies]\n");
        out.push_str("  soroban-sdk = { version = \"*\", features = [\"testutils\"] }\n");
    }
    if info.has_constructor {
        out.push_str(&format!(
            "\nnote: `{}` has a __constructor; real arguments were generated in the smoke test. Review and adjust them as needed.\n",
            info.contract_types.join(", ")
        ));
    }
    out.push_str("\nrun them with: cargo test\n");
    out
}

/// The `test-init` subcommand.
pub struct TestgenPlugin;

impl ForgePlugin for TestgenPlugin {
    fn name(&self) -> &'static str {
        "test-init"
    }

    fn command(&self) -> Command {
        Command::new("test-init")
            .about("Generate a test harness (fixtures, smoke test, snapshot helper) for an existing contract")
            .arg(
                Arg::new("path")
                    .long("path")
                    .help("Contract project directory [default: current directory]"),
            )
            .arg(
                Arg::new("force")
                    .long("force")
                    .action(ArgAction::SetTrue)
                    .help("Overwrite previously generated files"),
            )
    }

    fn run(&self, matches: &ArgMatches, ctx: &ForgeContext) -> Result<()> {
        let dir = matches
            .get_one::<String>("path")
            .map(|p| ctx.cwd.join(p))
            .unwrap_or_else(|| ctx.cwd.clone());

        let (info, written) = generate(&dir, matches.get_flag("force"))?;

        if ctx.json {
            let report = serde_json::json!({
                "contract_types": info.contract_types,
                "crate_name": info.crate_name,
                "package_name": info.package_name,
                "has_constructor": info.has_constructor,
                "has_testutils": info.has_testutils,
                "written_files": written
            });
            println!("{}", serde_json::to_string_pretty(&report).unwrap());
        } else if !ctx.quiet {
            print!("{}", format_report(&info, &written));
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use soroban_forge_scaffold as scaffold;

    fn hello_world_project(dir: &Path) {
        scaffold::generate(
            "hello-world",
            dir,
            &scaffold::project_vars("demo", "Test <t@example.com>"),
            false,
        )
        .unwrap();
    }

    fn contract_info(has_constructor: bool, has_testutils: bool) -> ContractInfo {
        ContractInfo {
            package_name: "demo".into(),
            crate_name: "demo".into(),
            contract_types: vec!["DemoContract".into()],
            has_constructor,
            has_testutils,
            constructor_args: "()".to_string(),
        }
    }

    fn multi_contract_info(has_constructor: bool, has_testutils: bool) -> ContractInfo {
        ContractInfo {
            package_name: "demo".into(),
            crate_name: "demo".into(),
            contract_types: vec!["Foo".into(), "Bar".into()],
            has_constructor,
            has_testutils,
            constructor_args: "()".to_string(),
        }
    }

    #[test]
    fn report_lists_generated_files() {
        let report = format_report(&contract_info(false, true), &["tests/a.rs", "tests/b.rs"]);
        assert!(report.contains("contract `DemoContract` (crate `demo`)"));
        assert!(report.contains("  tests/a.rs\n  tests/b.rs\n"));
    }

    #[test]
    fn report_explains_missing_testutils() {
        let report = format_report(&contract_info(false, false), &[]);
        assert!(report.contains("warning: dev-dependencies"));
        assert!(report.contains("features = [\"testutils\"]"));
    }

    #[test]
    fn report_explains_constructor_follow_up() {
        let report = format_report(&contract_info(true, true), &[]);
        assert!(report.contains("DemoContract` has a __constructor"));
        assert!(report.contains("real arguments were generated"));
    }

    #[test]
    fn generates_harness_for_hello_world_output() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("demo");
        hello_world_project(&dir);

        let (info, written) = generate(&dir, false).unwrap();
        assert_eq!(info.contract_types, vec!["HelloContract"]);
        assert!(!info.has_constructor);
        assert!(info.has_testutils);
        assert_eq!(written, vec!["tests/common/mod.rs", "tests/forge_smoke.rs"]);

        let smoke = std::fs::read_to_string(dir.join("tests/forge_smoke.rs")).unwrap();
        assert!(smoke.contains("use demo::{ HelloContract, HelloContractClient };"));
        assert!(smoke.contains("env.register(HelloContract, ())"));
        assert!(!smoke.contains("{{"));
    }

    #[test]
    fn constructor_contract_gets_sensible_default_arguments() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("tok");
        scaffold::generate("token", &dir, &scaffold::project_vars("tok", "T"), false).unwrap();

        let (info, _) = generate(&dir, false).unwrap();
        assert!(info.has_constructor);
        let smoke = std::fs::read_to_string(dir.join("tests/forge_smoke.rs")).unwrap();
        assert!(!smoke.contains("#[ignore]"));
        assert!(smoke.contains("common::new_account(&env)"));
        assert!(smoke.contains("soroban_sdk::String::from_str"));
    }

    #[test]
    fn refuses_to_overwrite_without_force() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("demo");
        hello_world_project(&dir);

        generate(&dir, false).unwrap();
        assert!(matches!(
            generate(&dir, false),
            Err(ForgeError::AlreadyExists(_))
        ));
        generate(&dir, true).unwrap();
    }

    #[test]
    fn errors_outside_a_cargo_project() {
        let tmp = tempfile::tempdir().unwrap();
        assert!(generate(tmp.path(), false).is_err());
    }

    // ── multi-contract tests ──

    #[test]
    fn to_snake_case_converts_camelcase() {
        assert_eq!(to_snake_case("HelloContract"), "hello_contract");
        assert_eq!(to_snake_case("Foo"), "foo");
        assert_eq!(to_snake_case("AB"), "a_b");
        assert_eq!(to_snake_case("a"), "a");
    }

    #[test]
    fn build_smoke_test_emits_one_test_per_contract() {
        let info = multi_contract_info(false, true);
        let smoke = build_smoke_test(&info);

        // Preamble present once.
        assert!(smoke.starts_with("//! Generated by"));
        assert!(smoke.contains("mod common;"));

        // Use statement lists all types.
        assert!(smoke.contains("use demo::{ Foo, FooClient, Bar, BarClient };"));

        // Two test functions.
        assert!(smoke.contains("fn foo_registers_and_client_constructs()"));
        assert!(smoke.contains("fn bar_registers_and_client_constructs()"));
        assert!(smoke.contains("env.register(Foo, ())"));
        assert!(smoke.contains("env.register(Bar, ())"));

        // No leftover template markers.
        assert!(!smoke.contains("{{"));
    }

    #[test]
    fn build_smoke_test_with_constructor_generates_default_arguments() {
        let info = multi_contract_info(true, true);
        let smoke = build_smoke_test(&info);
        assert!(!smoke.contains("#[ignore]"));
    }

    #[test]
    fn report_uses_plural_for_multiple_contracts() {
        let report = format_report(&multi_contract_info(false, true), &["tests/a.rs"]);
        assert!(report.contains("generated test harness for contracts `Foo, Bar` (crate `demo`)"));
    }

    #[test]
    fn report_uses_singular_for_single_contract() {
        let report = format_report(&contract_info(false, true), &["tests/a.rs"]);
        assert!(report.contains("generated test harness for contract `DemoContract` (crate `demo`)"));
    }

    #[test]
    fn generates_smoke_tests_for_multi_contract_project() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("multi");
        std::fs::create_dir_all(dir.join("src")).unwrap();
        std::fs::write(
            dir.join("Cargo.toml"),
            r#"
[package]
name = "multi-contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "1"

[dev-dependencies]
soroban-sdk = { version = "1", features = ["testutils"] }
"#,
        )
        .unwrap();
        std::fs::write(
            dir.join("src/lib.rs"),
            "#![no_std]\nuse soroban_sdk::{contract, contractimpl, Env};\n\n#[contract]\npub struct FirstContract;\n\n#[contractimpl]\nimpl FirstContract {\n    pub fn greet(env: Env) -> u32 { 42 }\n}\n\n#[contract]\npub struct SecondContract;\n\n#[contractimpl]\nimpl SecondContract {\n    pub fn greet(env: Env) -> u32 { 99 }\n}\n",
        )
        .unwrap();

        let (info, written) = generate(&dir, false).unwrap();
        assert_eq!(info.contract_types, vec!["FirstContract", "SecondContract"]);
        assert_eq!(written, vec!["tests/common/mod.rs", "tests/forge_smoke.rs"]);

        let smoke = std::fs::read_to_string(dir.join("tests/forge_smoke.rs")).unwrap();
        assert!(smoke.contains("fn first_contract_registers_and_client_constructs()"));
        assert!(smoke.contains("fn second_contract_registers_and_client_constructs()"));
        assert!(smoke.contains("env.register(FirstContract, ())"));
        assert!(smoke.contains("env.register(SecondContract, ())"));
        assert!(smoke.contains("FirstContractClient"));
        assert!(smoke.contains("SecondContractClient"));
    }
}
