//! English Auction contract — ascending price auction.
//!
//! An ascending-price auction where bidders place successively higher bids
//! within a fixed time window. The highest bidder at auction end wins the asset.
//!
//! Generated by [soroban-forge](https://github.com/soroban-forge-labs/soroban-forge).

#![no_std]

use soroban_sdk::{contract, contractimpl, contracttype, token, Address, Env};

#[contracttype]
#[derive(Clone, PartialEq, Eq, Debug)]
pub enum AuctionState {
    /// Initialized, waiting for seller to fund the asset.
    Pending,
    /// Funded and open for bidding.
    Open,
    /// Auction completed, highest bidder won.
    Settled,
    /// Canceled by seller before auction end.
    Canceled,
}

#[contracttype]
pub enum DataKey {
    Seller,
    AssetToken,
    PaymentToken,
    AssetAmount,
    ReservePrice,
    StartTime,
    Duration,
    State,
    HighestBidder,
    HighestBid,
    PreviousBidder,
    PreviousBid,
}

#[contract]
pub struct EnglishAuctionContract;

#[contractimpl]
impl EnglishAuctionContract {
    /// Initialize the English auction.
    ///
    /// * `seller` — address selling the asset
    /// * `asset_token` — contract address of the SEP-41 token being sold
    /// * `payment_token` — contract address of the SEP-41 token used for bidding
    /// * `asset_amount` — quantity of asset tokens offered for sale
    /// * `reserve_price` — minimum starting bid in payment tokens
    /// * `duration_seconds` — duration of the auction in seconds
    pub fn initialize(
        env: Env,
        seller: Address,
        asset_token: Address,
        payment_token: Address,
        asset_amount: i128,
        reserve_price: i128,
        duration_seconds: u64,
    ) {
        seller.require_auth();

        if env.storage().instance().has(&DataKey::Seller) {
            panic!("already initialized");
        }
        if asset_amount <= 0 {
            panic!("asset amount must be positive");
        }
        if reserve_price <= 0 {
            panic!("reserve price must be positive");
        }
        if duration_seconds == 0 {
            panic!("duration must be positive");
        }

        let now = env.ledger().timestamp();

        env.storage().instance().set(&DataKey::Seller, &seller);
        env.storage().instance().set(&DataKey::AssetToken, &asset_token);
        env.storage().instance().set(&DataKey::PaymentToken, &payment_token);
        env.storage().instance().set(&DataKey::AssetAmount, &asset_amount);
        env.storage().instance().set(&DataKey::ReservePrice, &reserve_price);
        env.storage().instance().set(&DataKey::StartTime, &now);
        env.storage().instance().set(&DataKey::Duration, &duration_seconds);
        env.storage().instance().set(&DataKey::State, &AuctionState::Pending);
    }

    /// Deposit the asset tokens into the auction contract to open bidding.
    ///
    /// Must be called by the `seller` after `initialize`.
    pub fn fund(env: Env) {
        let seller: Address = env.storage().instance().get(&DataKey::Seller).unwrap();
        let asset_token: Address = env.storage().instance().get(&DataKey::AssetToken).unwrap();
        let asset_amount: i128 = env.storage().instance().get(&DataKey::AssetAmount).unwrap();
        let state: AuctionState = env.storage().instance().get(&DataKey::State).unwrap();

        if state != AuctionState::Pending {
            panic!("can only fund from pending state");
        }

        seller.require_auth();

        token::Client::new(&env, &asset_token).transfer(
            &seller,
            &env.current_contract_address(),
            &asset_amount,
        );

        env.storage()
            .instance()
            .set(&DataKey::State, &AuctionState::Open);
    }

    /// Place a bid on the auction.
    ///
    /// The new bid must be higher than the current highest bid (or >= reserve price
    /// if no bids yet). Previous bidder's funds are returned.
    pub fn place_bid(env: Env, bidder: Address, bid_amount: i128) {
        bidder.require_auth();

        let state: AuctionState = env.storage().instance().get(&DataKey::State).unwrap();
        if state != AuctionState::Open {
            panic!("auction is not open for bidding");
        }

        let now = env.ledger().timestamp();
        let start_time: u64 = env.storage().instance().get(&DataKey::StartTime).unwrap();
        let duration: u64 = env.storage().instance().get(&DataKey::Duration).unwrap();
        let end_time = start_time + duration;

        if now > end_time {
            panic!("auction has ended");
        }

        let payment_token: Address = env.storage().instance().get(&DataKey::PaymentToken).unwrap();
        let reserve_price: i128 = env.storage().instance().get(&DataKey::ReservePrice).unwrap();

        let highest_bid: i128 = env
            .storage()
            .instance()
            .get(&DataKey::HighestBid)
            .unwrap_or(0);

        let min_required = if highest_bid == 0 {
            reserve_price
        } else {
            highest_bid + 1
        };

        if bid_amount < min_required {
            panic!("bid is too low");
        }

        if let Some(previous_bidder) = env.storage().instance().get::<_, Address>(&DataKey::HighestBidder) {
            let previous_bid: i128 = env.storage().instance().get(&DataKey::HighestBid).unwrap();
            token::Client::new(&env, &payment_token).transfer(
                &env.current_contract_address(),
                &previous_bidder,
                &previous_bid,
            );
        }

        token::Client::new(&env, &payment_token).transfer(&bidder, &env.current_contract_address(), &bid_amount);

        env.storage()
            .instance()
            .set(&DataKey::HighestBidder, &bidder);
        env.storage()
            .instance()
            .set(&DataKey::HighestBid, &bid_amount);
    }

    /// Close the auction and settle with the highest bidder.
    ///
    /// Seller receives payment, highest bidder receives asset.
    pub fn settle(env: Env) {
        let seller: Address = env.storage().instance().get(&DataKey::Seller).unwrap();
        let state: AuctionState = env.storage().instance().get(&DataKey::State).unwrap();

        if state != AuctionState::Open {
            panic!("auction is not open");
        }

        let now = env.ledger().timestamp();
        let start_time: u64 = env.storage().instance().get(&DataKey::StartTime).unwrap();
        let duration: u64 = env.storage().instance().get(&DataKey::Duration).unwrap();
        let end_time = start_time + duration;

        if now <= end_time {
            panic!("auction has not ended");
        }

        let highest_bidder_opt: Option<Address> = env.storage().instance().get(&DataKey::HighestBidder);

        match highest_bidder_opt {
            Some(highest_bidder) => {
                let asset_token: Address = env.storage().instance().get(&DataKey::AssetToken).unwrap();
                let asset_amount: i128 = env.storage().instance().get(&DataKey::AssetAmount).unwrap();
                let payment_token: Address = env.storage().instance().get(&DataKey::PaymentToken).unwrap();
                let highest_bid: i128 = env.storage().instance().get(&DataKey::HighestBid).unwrap();

                token::Client::new(&env, &asset_token).transfer(
                    &env.current_contract_address(),
                    &highest_bidder,
                    &asset_amount,
                );

                token::Client::new(&env, &payment_token).transfer(
                    &env.current_contract_address(),
                    &seller,
                    &highest_bid,
                );

                env.storage()
                    .instance()
                    .set(&DataKey::State, &AuctionState::Settled);
            }
            None => {
                panic!("no bids placed, cannot settle");
            }
        }
    }

    /// Cancel the auction and return the asset to the seller.
    ///
    /// Can only be called by the seller before auction end.
    pub fn cancel(env: Env) {
        let seller: Address = env.storage().instance().get(&DataKey::Seller).unwrap();
        let state: AuctionState = env.storage().instance().get(&DataKey::State).unwrap();

        if state != AuctionState::Open {
            panic!("auction is not open");
        }

        seller.require_auth();

        let asset_token: Address = env.storage().instance().get(&DataKey::AssetToken).unwrap();
        let asset_amount: i128 = env.storage().instance().get(&DataKey::AssetAmount).unwrap();

        token::Client::new(&env, &asset_token).transfer(
            &env.current_contract_address(),
            &seller,
            &asset_amount,
        );

        if let Some(highest_bidder) = env.storage().instance().get::<_, Address>(&DataKey::HighestBidder) {
            let payment_token: Address = env.storage().instance().get(&DataKey::PaymentToken).unwrap();
            let highest_bid: i128 = env.storage().instance().get(&DataKey::HighestBid).unwrap();

            token::Client::new(&env, &payment_token).transfer(
                &env.current_contract_address(),
                &highest_bidder,
                &highest_bid,
            );
        }

        env.storage()
            .instance()
            .set(&DataKey::State, &AuctionState::Canceled);
    }

    /// Get the current highest bid and bidder.
    pub fn get_highest_bid(env: Env) -> (Option<Address>, i128) {
        let bidder: Option<Address> = env.storage().instance().get(&DataKey::HighestBidder);
        let bid: i128 = env
            .storage()
            .instance()
            .get(&DataKey::HighestBid)
            .unwrap_or(0);
        (bidder, bid)
    }

    /// Get the current auction state.
    pub fn get_state(env: Env) -> AuctionState {
        env.storage()
            .instance()
            .get(&DataKey::State)
            .unwrap_or(AuctionState::Pending)
    }
}

#[cfg(test)]
mod test;
