//! Merkle airdrop — one claim per eligible address, proven against a root.
//!
//! An allowlist of `(address, amount)` entries can be arbitrarily large
//! without paying to store it on-chain: the tree is built off-chain and only
//! its 32-byte root lives in the contract.
//!
//! * **Leaf** — `sha256(xdr(address) || be_bytes(amount))`, so a proof binds
//!   the claimant *and* the amount; neither can be swapped for another.
//! * **Proof** — the sibling hashes from the leaf up to the root. Pairs are
//!   hashed in sorted order (`sha256(min || max)`), which makes the proof
//!   order-independent so no left/right flags are needed.
//! * **One claim** — a marker per claimant is written before the transfer, so
//!   a second claim is rejected even with a valid proof.
//!
//! Build the same tree off-chain with the `leaf` and pair-hash rules above —
//! `leaf` is exposed as an entrypoint so a script can cross-check its own
//! hashing against the contract's.
//!
//! Generated by [soroban-forge](https://github.com/soroban-forge-labs/soroban-forge).

#![no_std]

use soroban_sdk::{
    contract, contractimpl, contracttype, token, xdr::ToXdr, Address, Bytes, BytesN, Env, Vec,
};

/// Claim markers are persistent (they must outlive the instance), so they are
/// bumped past the archival threshold as they are written.
const CLAIM_TTL_THRESHOLD: u32 = 518_400; // ~30 days of ledgers
const CLAIM_TTL_EXTEND_TO: u32 = 1_036_800; // ~60 days of ledgers

#[contracttype]
pub enum DataKey {
    Admin,
    Token,
    Root,
    /// Amount an address has already claimed.
    Claimed(Address),
}

#[contract]
pub struct MerkleAirdropContract;

#[contractimpl]
impl MerkleAirdropContract {
    /// Configure the airdrop.
    ///
    /// * `admin` — address that funds the contract and may replace the root
    /// * `token` — contract address of the SEP-41 token being distributed
    /// * `root`  — merkle root of the `(address, amount)` allowlist
    pub fn initialize(env: Env, admin: Address, token: Address, root: BytesN<32>) {
        admin.require_auth();
        env.storage().instance().set(&DataKey::Admin, &admin);
        env.storage().instance().set(&DataKey::Token, &token);
        env.storage().instance().set(&DataKey::Root, &root);
    }

    /// Deposit `amount` tokens from the admin so claims can be paid out.
    pub fn fund(env: Env, amount: i128) {
        let admin = Self::admin(env.clone());
        admin.require_auth();
        if amount <= 0 {
            panic!("amount must be positive");
        }
        let token: Address = env.storage().instance().get(&DataKey::Token).unwrap();
        let airdrop = env.current_contract_address();
        token::Client::new(&env, &token).transfer(&admin, &airdrop, &amount);
    }

    /// Replace the merkle root, e.g. for a second airdrop round (admin only).
    pub fn set_root(env: Env, root: BytesN<32>) {
        Self::admin(env.clone()).require_auth();
        env.storage().instance().set(&DataKey::Root, &root);
    }

    /// The merkle root currently accepted by `claim`.
    pub fn root(env: Env) -> BytesN<32> {
        env.storage().instance().get(&DataKey::Root).unwrap()
    }

    /// The configured admin.
    pub fn admin(env: Env) -> Address {
        env.storage().instance().get(&DataKey::Admin).unwrap()
    }

    /// The leaf hash for one allowlist entry: `sha256(xdr(claimant) || amount)`.
    ///
    /// Exposed so off-chain tree builders can verify they hash leaves exactly
    /// the way the contract does.
    pub fn leaf(env: Env, claimant: Address, amount: i128) -> BytesN<32> {
        let mut buf = Bytes::new(&env);
        buf.append(&claimant.to_xdr(&env));
        buf.extend_from_array(&amount.to_be_bytes());
        env.crypto().sha256(&buf).into()
    }

    /// Whether `claimant` has already claimed.
    pub fn has_claimed(env: Env, claimant: Address) -> bool {
        env.storage().persistent().has(&DataKey::Claimed(claimant))
    }

    /// Amount `claimant` received, or `0` if they have not claimed.
    pub fn claimed_amount(env: Env, claimant: Address) -> i128 {
        env.storage()
            .persistent()
            .get(&DataKey::Claimed(claimant))
            .unwrap_or(0)
    }

    /// Whether `proof` shows `(claimant, amount)` is in the current root.
    ///
    /// A read-only check — useful for a UI that wants to grey out an
    /// ineligible address instead of letting the claim revert.
    pub fn verify(env: Env, claimant: Address, amount: i128, proof: Vec<BytesN<32>>) -> bool {
        let mut node = Self::leaf(env.clone(), claimant, amount);
        for sibling in proof.iter() {
            node = hash_pair(&env, &node, &sibling);
        }
        node == Self::root(env)
    }

    /// Claim `amount` for `claimant` against the current root.
    ///
    /// Returns the amount transferred. Panics when the claimant already
    /// claimed or the proof does not reproduce the root.
    pub fn claim(env: Env, claimant: Address, amount: i128, proof: Vec<BytesN<32>>) -> i128 {
        claimant.require_auth();
        if amount <= 0 {
            panic!("amount must be positive");
        }
        if Self::has_claimed(env.clone(), claimant.clone()) {
            panic!("already claimed");
        }
        if !Self::verify(env.clone(), claimant.clone(), amount, proof) {
            panic!("invalid proof");
        }

        // Mark before transferring so a re-entrant token can't double-pay.
        let key = DataKey::Claimed(claimant.clone());
        env.storage().persistent().set(&key, &amount);
        env.storage()
            .persistent()
            .extend_ttl(&key, CLAIM_TTL_THRESHOLD, CLAIM_TTL_EXTEND_TO);

        let token: Address = env.storage().instance().get(&DataKey::Token).unwrap();
        token::Client::new(&env, &token).transfer(
            &env.current_contract_address(),
            &claimant,
            &amount,
        );

        amount
    }

    /// Return everything still held by the contract to the admin, e.g. once
    /// the claim window has closed.
    pub fn sweep(env: Env) -> i128 {
        let admin = Self::admin(env.clone());
        admin.require_auth();

        let token: Address = env.storage().instance().get(&DataKey::Token).unwrap();
        let client = token::Client::new(&env, &token);
        let balance = client.balance(&env.current_contract_address());
        if balance <= 0 {
            panic!("nothing to sweep");
        }
        client.transfer(&env.current_contract_address(), &admin, &balance);
        balance
    }
}

/// Hash two nodes in sorted order, so a proof carries only sibling hashes and
/// never needs to say which side each one was on.
fn hash_pair(env: &Env, a: &BytesN<32>, b: &BytesN<32>) -> BytesN<32> {
    let (first, second) = if a < b { (a, b) } else { (b, a) };
    let mut buf = Bytes::new(env);
    buf.extend_from_array(&first.to_array());
    buf.extend_from_array(&second.to_array());
    env.crypto().sha256(&buf).into()
}

#[cfg(test)]
mod test;
