//! Token vesting with cliff + linear release schedule.
//!
//! Tokens are locked in the contract and become claimable by a beneficiary
//! over time according to a configurable vesting schedule:
//!
//! * **Cliff** — no tokens are claimable until a duration (in seconds) has
//!   passed since the contract was initialized.
//! * **Linear release** — after the cliff, tokens vest continuously at a
//!   constant rate over the remaining vesting duration.
//! * **Claim** — the beneficiary may call `claim` at any point; the contract
//!   transfers the newly vested amount since the last claim.
//!
//! Generated by [soroban-forge](https://github.com/soroban-forge-labs/soroban-forge).

#![no_std]

use soroban_sdk::{contract, contractimpl, contracttype, token, Address, Env};

#[contracttype]
pub enum DataKey {
    Admin,
    Token,
    Beneficiary,
    Start,
    Cliff,
    End,
    TotalAmount,
    Claimed,
}

#[contract]
pub struct VestingContract;

#[contractimpl]
impl VestingContract {
    /// Initialize the vesting schedule.
    ///
    /// * `admin` — address that will fund the contract with tokens
    /// * `token` — contract address of the SEP-41 token to vest
    /// * `beneficiary` — address that receives vested tokens
    /// * `cliff_duration` — seconds from now until first tokens vest
    /// * `vesting_duration` — seconds from cliff end until fully vested
    /// * `total_amount` — total tokens to vest over the schedule
    pub fn initialize(
        env: Env,
        admin: Address,
        token: Address,
        beneficiary: Address,
        cliff_duration: u64,
        vesting_duration: u64,
        total_amount: i128,
    ) {
        admin.require_auth();

        if env.storage().instance().has(&DataKey::Admin) {
            panic!("already initialized");
        }

        if total_amount <= 0 {
            panic!("total amount must be positive");
        }

        let now = env.ledger().timestamp();

        env.storage().instance().set(&DataKey::Admin, &admin);
        env.storage().instance().set(&DataKey::Token, &token);
        env.storage()
            .instance()
            .set(&DataKey::Beneficiary, &beneficiary);
        env.storage().instance().set(&DataKey::Start, &now);
        env.storage()
            .instance()
            .set(&DataKey::Cliff, &(now + cliff_duration));
        env.storage()
            .instance()
            .set(&DataKey::End, &(now + cliff_duration + vesting_duration));
        env.storage()
            .instance()
            .set(&DataKey::TotalAmount, &total_amount);
        env.storage().instance().set(&DataKey::Claimed, &0_i128);
    }

    /// Deposit the full vesting amount into this contract.
    ///
    /// Must be called by the `admin` after `initialize`.
    pub fn fund(env: Env) {
        let admin: Address = env.storage().instance().get(&DataKey::Admin).unwrap();
        admin.require_auth();

        let token: Address = env.storage().instance().get(&DataKey::Token).unwrap();
        let total_amount: i128 = env.storage().instance().get(&DataKey::TotalAmount).unwrap();

        let client = token::Client::new(&env, &token);
        client.transfer(&admin, &env.current_contract_address(), &total_amount);
    }

    /// Return the amount of tokens vested so far according to the schedule.
    pub fn get_vested_amount(env: Env) -> i128 {
        let now = env.ledger().timestamp();
        let cliff: u64 = env.storage().instance().get(&DataKey::Cliff).unwrap();
        let end: u64 = env.storage().instance().get(&DataKey::End).unwrap();
        let total_amount: i128 = env.storage().instance().get(&DataKey::TotalAmount).unwrap();

        if now < cliff {
            return 0;
        }
        if now >= end {
            return total_amount;
        }

        // Linear interpolation: total * (now - cliff) / (end - cliff)
        let elapsed = now - cliff;
        let duration = end - cliff;
        // Use u128 for the multiplication to avoid overflow, then cast back.
        let vested = (total_amount as u128 * elapsed as u128 / duration as u128) as i128;
        vested
    }

    /// Return the amount that the beneficiary can currently claim
    /// (vested minus already claimed).
    pub fn get_claimable_amount(env: Env) -> i128 {
        let vested = Self::get_vested_amount(env.clone());
        let claimed: i128 = env.storage().instance().get(&DataKey::Claimed).unwrap();
        vested - claimed
    }

    /// Claim all currently vested tokens for the beneficiary.
    ///
    /// Transfers the newly vested amount (since the last claim) to the
    /// beneficiary. Can be called multiple times.
    pub fn claim(env: Env) -> i128 {
        let beneficiary: Address =
            env.storage().instance().get(&DataKey::Beneficiary).unwrap();
        beneficiary.require_auth();

        let claimable = Self::get_claimable_amount(env.clone());
        if claimable <= 0 {
            panic!("nothing to claim");
        }

        let claimed: i128 = env.storage().instance().get(&DataKey::Claimed).unwrap();
        env.storage()
            .instance()
            .set(&DataKey::Claimed, &(claimed + claimable));

        let token: Address = env.storage().instance().get(&DataKey::Token).unwrap();
        let client = token::Client::new(&env, &token);
        client.transfer(
            &env.current_contract_address(),
            &beneficiary,
            &claimable,
        );

        claimable
    }
}

#[cfg(test)]
mod test;
