//! Generated by `soroban-forge test-init`. Grow it into your real test suite.

mod common;

use hello_forge::{ HelloContract, HelloContractClient };

#[test]
fn contract_registers_and_client_constructs() {
    let env = common::test_env();
    let contract_id = env.register(HelloContract, ());
    let _client = HelloContractClient::new(&env, &contract_id);
}
